### ISSUE TITLE
package request for arch linux

### ISSUE THREAD

**Issue by CRAG666** [jbuchermn/newm#1]
Your work looks spectacular, I have tried to install it but I have not yet been able to, I would like to use your project for my desktop for daily use, I use arch linux I think it would be great if there was a package there

**Comment by jbuchermn** [comment]
Thanks for this suggestion. I'm planning to do so, but the last couple of weeks haven't really had any time to work on newm. As a first step I'm going to improve documentation for v0.1 and merge the branch. Afterwards an AUR package seems like a logical next step.

**Comment by CRAG666** [comment]
Before closing this. I just add that this project excited me a lot regarding the future of linux

**Comment by jbuchermn** [comment]
Thanks a lot!
