### ISSUE TITLE
electron apps don't work with wayland flags

### ISSUE THREAD

**Issue by CRAG666** [jbuchermn/newm#10]
I just compiled the v2 of newm and if everything works fine the shape rendering part is solved, now the problem is that when trying to open google chrome with the flags so that it runs native in wayland it does not open. Before changing to version 2 the application did open. I provided more electron applications and the error was the same.
i will also show the configuration i currently have
![start newm](https://i.ibb.co/m9XQt04/screen-1636654275.png)
![environment vars](https://i.ibb.co/NmFWVCD/screen-1636654299.png)

**Comment by jbuchermn** [comment]
Can you post the error message running

```
chromium --enable-features=UseOzonePlatform --ozone-platform=wayland
```

**Comment by jbuchermn** [comment]
Second question.. does it work on v0.2 if you're only using one monitor?

**Comment by CRAG666** [comment]
I just tried it with a single monitor and it still doesn't work. Like I said before everything works great even with two monitors. Only electron apps with wayland flags don't seem to do it.

![not found](https://i.ibb.co/qW35Nvw/screen-1636657980.png)

With the master branch this problem did not happen. Now that I try to print grim -g "$ (slurp)" ~ / screen - "$ (date +% s)". Png, I could not select a region, the cursor is fully freeze.

**Comment by CRAG666** [comment]
In the image I try edge but in chrome it is the same error

**Comment by jbuchermn** [comment]
Aaah sorry, I just remembered, I actually encountered this as well. The source is an update in wlroots, which only v0.2 contains.

See [wlroots issue](https://github.com/swaywm/wlroots/issues/3168) and [chromium bug](https://bugs.chromium.org/p/chromium/issues/detail?id=1246834).

To get it running I actually have a patched version of wlroots, where I undid this [commit](https://github.com/swaywm/wlroots/commit/d290b13871fa18dcad6cd90d9ee93e7205742124?diff=unified). But according to the wlroots github issue mentioned above, updating chromium could also do the trick.

**Comment by CRAG666** [comment]
OK, I have the newest version of google-chrome, could you tell me how to fix it, right now I also open an issue with the problem that I messed up when taking screenshots

**Comment by jbuchermn** [comment]
You'll need (probably - haven't tried)

```
git clone --recursive-submodules --branch v0.2 https://github.com/jbuchermn/pywm
cd pywm/subprojects/wlroots
[wlroots_patch.txt](https://github.com/jbuchermn/newm/files/7522929/wlroots_patch.txt)
git apply ~/Downloads/wlroots_patch.txt
cd ../..
pip install --user .
```

**Comment by CRAG666** [comment]
I will not close the issue yet, I will do all the possible tests and I will also wait for on_startup to be implemented in order to test complete the flow

**Comment by jbuchermn** [comment]
Just try the patch first, which should fix chromium. If electron works, this issue will be closed. For the other topics there are separate issues.

**Comment by CRAG666** [comment]
The problem is resolved, I just want that solution to be part of the later versions. and another thing check the pkbuild in arch, it seems that it is being built with another version different from the one written so it is marked as outdated, you can verify what I tell you doing makepkg -sc and install and then check with yay -Syyu that it marks it as outdated

**Comment by CRAG666** [comment]
![no select area](https://i.ibb.co/h7pkbgv/screen-1636663874.png)
I still cannot share screen, but I better recognize the error, this is because I cannot select the screen, whether it is with or without another monitor, in swaywm the cursor takes the form of a cross, action that does not happen in newm

**Comment by jbuchermn** [comment]
Closing as this is handled in #17.
