### ISSUE TITLE
Not able to compile it on Debian 11 LTS. 

### ISSUE THREAD

**Issue by Mesum-Hussain** [jbuchermn/newm#104]
Can't compile on Debian 11 LTS because it requires newer version of Meson. 
Compiling from source is the only option on Debian 11 because using pip requires us to access github and github is not allowing to login using your password, we are supposed to login using a token which is very long and complicated and practically impossible to type in a TTY where you can't see the password while typing.

If the dependencies are used such that their versions are compatible what's provided in Debian LTS, then all the distros will be able to compile NEWM, because Debian LTS has the oldest packages compared to any other distro. 

So I request you to use the versions of the dependencies which are available in the latest Debian LTS.

**Comment by jbuchermn** [comment]
I myself am not interested in Debian, but I'll surely accept a PR if it doesn't break compatibility with Arch and NixOS. 

Adjusting the meson version should be possible quite quickly, so feel free to open a PR :)

**Comment by Mesum-Hussain** [comment]
I am new to development so I don't know how to do this. Can you please at least guide me how to do it? 
Just tell me how to change the version. I will look up how to open a pull request.
Thanks for considering btw.

**Comment by jbuchermn** [comment]
Yeah I think this is the file to change.

Although taking a look at wlroots `meson.build` it appears that they require meson 0.58.1 at least. So I'm not sure this is going to work...

**Comment by Mesum-Hussain** [comment]
Yes you are right. It is saying that this project requires version greater than 0.58.1.
Maybe it's not possible to get it working on Debian LTS unfortunately. I guess I will try Testing branch then. Or maybe give another short to Alpine (didn't wen't well the last time I tried though). 
Anyways thanks for your help.
