### ISSUE TITLE
Error: signal 11

### ISSUE THREAD

**Issue by Ehiffi** [jbuchermn/newm#106]
System cfg: laptop
Intel i3 3110m 2,4 GHz
Intel HD 4000
Ram 4gb

I guess the issue is hardware too slow, but I don't know what signal 11 mean so idk

**Comment by Ehiffi** [comment]
Error signal was in log file

**Comment by CRAG666** [comment]
please i need your log file

**Comment by jbuchermn** [comment]
Hey,

signal 11 is a segfault, which is a bug. Probably realted to https://github.com/jbuchermn/pywm/issues/10

A log would help.

**Comment by jbuchermn** [comment]
Closing in favour of #109
