### ISSUE TITLE
Keybinding issues

### ISSUE THREAD

**Issue by lidgnulinux** [jbuchermn/newm#107]
Hello, I finally able to compile newm on my debian. I'm facing a glitch or stutter (I'm not sure what's called). I have dual graphic : Intel and nvidia, the nvidia one is not active so it's just intel.
Any good advice to prevent newm to glitch like this ? if it's hardware's fault then it's done. The other compositors are fine and I don't face something like this. Thanks.

> [ahmad ~]$ lspci | grep VGA
> 00:02.0 VGA compatible controller: Intel Corporation 2nd Generation Core Processor Family Integrated Graphics Controller (rev 09) 
> 01:00.0 VGA compatible controller: NVIDIA Corporation GF119M [GeForce GT 520M] (rev a1)

![2022-05-07T10:31:41,994634919+07:00](https://user-images.githubusercontent.com/99301306/167249924-fd68d552-7f99-40be-ad4a-824cb54c2c21.png)

**Comment by lidgnulinux** [comment]
newm log : 
[newm_log.txt](https://github.com/jbuchermn/newm/files/8644962/newm_log.txt)
newm config : 
[config.txt](https://github.com/jbuchermn/newm/files/8644965/config.txt)

**Comment by CRAG666** [comment]
@lidgnulinux You could use my configuration and check if the problem persists, it's in my dot files(use v3 branch), obviously modify according to your preferences, also don't forget to read the tips and tricks and systemd support.

**Comment by CRAG666** [comment]
I just read your configuration, it seems to me that you are still using v2, you could try using v3, in v3 many of those problems are solved. Greetings

**Comment by lidgnulinux** [comment]
> I just read your configuration, it seems to me that you are still using v2, you could try using v3, in v3 many of those problems are solved. Greetings

Thanks @CRAG666 , I'll try it soon.

**Comment by lidgnulinux** [comment]
Sadly most of keybinds or shortcuts don't work,  I don't know why, I try to change keyboard layout but it gives no effect.

**Comment by CRAG666** [comment]
Ok, that's because I use many xf86 keys, but put the conventions you want, you can even use the ones you already have in v2

**Comment by lidgnulinux** [comment]
Yeah, I adjust it too, but still no luck.

**Comment by lidgnulinux** [comment]
The only working shortcuts are overview (when I press LOGO) and kill window. Dunno why. Indeed I'm no longer get glitch with configv3 configuration but can't use shortcuts is weird.

**Comment by jbuchermn** [comment]
Can you post the relevant config excerpts? I think there have been some recent changes

**Comment by lidgnulinux** [comment]
Hi, @jbuchermn , I use [this config](https://raw.githubusercontent.com/jbuchermn/newm/master/newm/default_config.py), I changed it on "output" and terminal shortcut.

**Comment by jbuchermn** [comment]
This uses the old format with "M-" and "ModPress". If you're on the most recent v0.3 this does not work anymore, as it has been generalized (see e.g. https://github.com/jbuchermn/newm/blob/v0.3/newm/default_config.py)

Basically instead of "M" use "S", "L", "C", "A", "1", "2" or "3" for Shift, Logo, Control, Alt, Mod1, Mod2, Mod3.

Instead of "ModPress" use "L-" e.g. if you want your Mod to be Logo.

**Comment by lidgnulinux** [comment]
Hi @jbuchermn , it somehow fixed, no more glitch, I just need to use default config from ~/.local/lib/<newm library path>/default_config.py,  but when I move that config to ~/.config/newm it causes glitch.

**Comment by lidgnulinux** [comment]
@jbuchermn , oh perhaps I need to use "stutter" term, it's like when you open window and then move it, there is artifact left.
