### ISSUE TITLE
Process on start

### ISSUE THREAD

**Issue by CRAG666** [jbuchermn/newm#11]
How can I start applications at the start of newm. In sway that can be done just by writing exec in the configuration file, this as it is done in newm, I did this but I don't know if it is working, since I inspect with htop and the process does not appear, I have the impression that the process is added to the newm startup process but I don't know if this is true, I also wanted to use subprocess for this task. Enlighten me please.
![cofig file newm](https://i.ibb.co/6nQj1nM/screen-1636654090.png)

**Comment by jbuchermn** [comment]
Currently there is no configuration option for that, but this possibly should be added. Doing it like you do it could be a valid way, just know that the script gets executed any time you reload the config (default `Super-C`). Also this gets executed before the compositor is started, maybe therefore your processes crash?

**Comment by CRAG666** [comment]
That seems to be the problem. I imagine a solution similar to how the keymap defines, a function called on_startup that returns a tuple with the commands to execute. But it is only an idea.

**Comment by jbuchermn** [comment]
That's a good idea! Actually it can be even simpler: Just a function, `on_startup` called after the compositor has started (and possibly after a config reload `on_reconfigure`), in which you can `os.system` whatever you want.

I'll add that shortly into v0.2, should only be a couple of lines.

**Comment by CRAG666** [comment]
Well I'll wait, it would also be good to see an example of the configuration of this new feature in the README.md so that you can copy and adapt it.

**Comment by jbuchermn** [comment]
Just pushed to branch v0.2 with a little example

**Comment by CRAG666** [comment]
Just as I imagined it, it looks very good, each time it becomes what sway is, but newm is more beautiful and usable. I just patch to use electron and uninstall swaywm. this project is a good complement to newm https://github.com/otsaloma/catapult, I recommend it, it is an incredible launcher
