### ISSUE TITLE
Space / room to interact.

### ISSUE THREAD

**Issue by lidgnulinux** [jbuchermn/newm#110]
Hi, I'm not sure if it's necessary, are there space / room to interact like irc / matrix room / discord channel I can join ? since there are many petty questions I need to ask, instead of open new issue. Thanks.

**Comment by jbuchermn** [comment]
That's a good point. I did set up a gitter some time ago - maybe we can use that

https://gitter.im/jbuchermn-newm/community#

**Comment by jbuchermn** [comment]
Closing this as linked from readme
