### ISSUE TITLE
Fullscreening a window from a stack scales the whole stack instead.

### ISSUE THREAD

**Issue by xPMo** [jbuchermn/newm#117]
Expected behavior: The focused window should be resized to fit the screen, and no other windows should be visible.

Actual behavior: The focused window will not take up the whole screen, but will instead be slightly smaller (like it is in a stack compared to an unstacked column), and all windows from the stack are scaled by roughly the same proportion.

**Comment by jbuchermn** [comment]
Should be fixed now
