### ISSUE TITLE
Error select area with slurp

### ISSUE THREAD

**Issue by CRAG666** [jbuchermn/newm#12]
Now that I try to print grim -g "$ (slurp)" ~ / screen - "$ (date +% s)". Png, I could not select a region, the cursor is fully freeze. I can't do anything other than forcibly shutting down the laptop

**Comment by jbuchermn** [comment]
same as in #8 - layer shell isn't supported. However newm should not crash from this.. Can you post the exact command you were running? If I try

```
slurp
```

I just get

```
compositor doesn't support zwlr_layer_shell_v1
```

**Comment by CRAG666** [comment]
grim -g "$ (slurp)" ~ / screen - "$ (date +% s)". png

**Comment by jbuchermn** [comment]
There's a lot of spaces in that command, that I think should not be there. This just outputs

```
invalid geometry
```

**Comment by CRAG666** [comment]
grim -g "$(slurp)" ~/screen-"$(date +%s)".png
this is if the command does not know why the previous one went with spaces

**Comment by jbuchermn** [comment]
Okay thanks, does this crash every time? I just get the expected result...

```
compositor doesn't support zwlr_layer_shell_v1
invalid geometry
```

**Comment by CRAG666** [comment]
yes, It fails only when I try to select, although I can take screenshots but to the entire screen.
