### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by jkim5959** [jbuchermn/newm#126]
I did a fresh arch install.

minimal, no x or wayland, just nano and git and yay without any display server, which is probably why i'm getting this issue.

I installed newm through yay -S newm-git

start-newm -d gives me the following log. at ~/.cache/newm_log.

![VirtualBox_Arch_06_07_2022_23_27_20](https://user-images.githubusercontent.com/85728320/177561543-f2f74305-aae8-41d1-a523-ba91d8ade152.png)

**Comment by CRAG666** [comment]
@xPMo Should be added as wob unit, brightnessctl as they are part of some newm utilities, do not forget to update srinfo

**Comment by xPMo** [comment]
Nice, thanks. `seatd` is required, but `wob` and `brightnessctl` are just part of the default config. I'll add them to the `optdepends`

**Comment by xPMo** [comment]
@jkim5959 It looks like `seatd` got pulled in correctly, it's just erroring out for some reason.

I see it trying to connect to `/run/seatd.s...` (almost certainly `/run/seatd.sock`). You might try [these steps wrt seatd+Sway](https://wiki.archlinux.org/title/Sway#Starting)
