### ISSUE TITLE
first impressions, discussions

### ISSUE THREAD

**Issue by edrex** [jbuchermn/newm#127]
Hi @jbuchermn! 
I played around with newm for 30 minutes or so today, and I'm impressed from a HCI design perspective
as well as with the level of completeness and polish the project already shows.

I sense that we are interested in exploring overlapping subsets of the graphical shell solution space, and I love that you spun off pywm, since I am very interested in creating my own compositor as a testbed for some context-driven shell ideas.

First impressions:
- Grid wall seems like a solid spatial UI metaphor, especially with a functional ZUI.
- Swipe, pointer, keyboard motions started to feel pretty useable by the end of the session/
- the motion design is mostly snappy and understated

Issues:
- Shifting focus with Mod+[hjklunt] seems uncomfortably laggy, maybe due to some gesture processing latency? (I'm also testing keyd, a uinput key remapping daemon, so that might be a factor)
- No touchscreen support (my laptop has a touch screen)

Styling:
- The light blue halo around the focused window was hard for me to see, especially against the default bluish background (I'm outside)

I still need to work through getting my session/environment set up, and I'm hoping after that everything I need to will be working and I can try using it for a longer session.

**Meta:** Do you think enabling discussions for this repo would be a good idea?

**Comment by CRAG666** [comment]
Hi you could try to try my settings, I also use keyd. in the case of the edge of sale is something you can remove, I did not hear it before now if I use it

**Comment by edrex** [comment]
Closing to continue elsewhere

- Touch screen support #112

> Shifting focus with Mod+[hjklunt] seems uncomfortably laggy

- Opened #128 since I didn't see an existing issue.

> Meta: Do you think enabling discussions for this repo would be a good idea?

Found https://github.com/jbuchermn/newm/issues/71#issuecomment-1061113738

> I created a gitter community: https://gitter.im/jbuchermn-newm/community# Let's see how this works, I've never used that before. :)


(re: @CRAG666 I'm going to drop keyd. While there are some limited use cases where global input overrides make sense, straight key remapping is the only one I care about, and I already do that via a set of udev rules. Most of what keyd does would make more sense as a library embedded in your shell etc IMO.)
