### ISSUE TITLE
layout.move(): skip animation when no panning is needed

### ISSUE THREAD

**Issue by edrex** [jbuchermn/newm#128]
As a new user, I perceived an uncomfortable period of delay when moving focus between windows with the keyboard motions. I believe this is because even when no panning is needed,  `layout.move(...)` waits out the animation period before updating the focus halo.

**Suggested change:** when no panning is needed, `layout.move(...)` could skip animation or otherwise tighten it up.

## Reports

From new user experience report #127:

> Shifting focus with Mod+[hjklunt] seems uncomfortably laggy, maybe due to some gesture processing latency?

Also I think this is the nit [mentioned](https://github.com/jbuchermn/newm/issues/71#issuecomment-1057426786) by @sadrach-cl.

> Now, how can I (...) increase the speed when pressing commands like "logo+HJKL"?

**Comment by jbuchermn** [comment]
Thanks for reporting! You're completely right in diagnosing the problem; actually that's been bothering me for some time but I haven't come round to fixing it.

I'll take a look, this should be really straight-forward.

**Comment by jbuchermn** [comment]
I just pushed to master - can you try?

**Comment by edrex** [comment]
- The blue focus halo seems gone, not sure if that's a side effect of skipping animation.
- The time till the window shows focus (terminal cursor goes solid) is reduced (from ~400ms to ~100ms)

It seems like there is still some delay, perceptible but small. Maybe a different cause?

**Comment by jbuchermn** [comment]
It's weird that the blue halo (in config it's called `focus_border`) is gone for you. I don't experience any issues with it.

Did you change anything concerning the relevant configuration?

I'd focus on that first, maybe there is some issue causing related delay
