### ISSUE TITLE
focus_follows_mouse fails when transitioning from gutter/background surface to window

### ISSUE THREAD

**Issue by edrex** [jbuchermn/newm#129]
When moving the pointer between windows, the destination window sometimes fails to receive focus. The condition for failure seems to be if the cursor transitions to the gutter/background surface in between. Whenever the cursor transitions from background to window, focus doesn't follow correctly.

Moving the pointer quickly between windows focuses correctly, I think because the pointer "tunnels" across the gutter without registering an intermediate position.

**Comment by jbuchermn** [comment]
I've never noticed something like that.. What do you mean by gutter? 

Can you record a short clip showing what is going wrong?

**Comment by a-priestley** [comment]
Hello.
I am noticing this too. For me specifically it causes the border to show up around my alacritty window, but the window itself does not gain focus--the application is not actionable. I believe what @edrex means by "gutter", is the gaps present between two windows. If I overlap the windows and then hover from one over to alacritty, it gains focus. But when hovering from blank compositor space (desktop, or "gaps"), alacritty intermittently fails to properly gain focus.

**Comment by SwitchAxe** [comment]
I also have this issue. Have you managed to find a workaround? Is there going to be a fix? Maybe some logging can help...? If so, which kind of log is needed to track down the problem?
