### ISSUE TITLE
How to install newm in Ubuntu?

### ISSUE THREAD

**Issue by apandada1** [jbuchermn/newm#137]
There was a recent question in [Ask Ubuntu](https://askubuntu.com/q/1421066/124466) about the installation procedure of newm in Ubuntu.

Can someone provide a step by step instruction to install newm from the source?

Let's target the latest version, 22.04 LTS.

**Comment by CRAG666** [comment]
This is quite simple, just install the dependencies, if you like it, I leave them and then just follow the instructions of the installation with pip

**Comment by godalming123** [comment]
@jbuchermn I might be missing something, but I cannot seem to find a list of dependency's I have tried installing the following on ubuntu server 22.04:
* meson
* libwayland-server0
* libwayland-client0
* libwayland-cursor0
* libwlroots10
* libwayland-bin
* libwayland-dev
* wayland-protocols
but still get an error when trying to install pywm with pip saying that wayland-server is not installed, I can create a seperate issue if you like but am hoping that this will be easy enough to fix so I do not have to do that.
