### ISSUE TITLE
Providing newm + pywm packages for gentoo

### ISSUE THREAD

**Issue by x0rzavi** [jbuchermn/newm#138]
I've made an ebuild (synonymous to PKGBUILD on Arch) for both newm and pywm accessible from https://github.com/x0rzavi/x0rzavi-overlay which I'm sure will encourage more people to try out this awesome compositor. 
As of now the packages build directly from the latest commit and needs more testing, but I'm planning to do the following:

- Add stable versioned packages
- Improve dependency resolution (Not quite sure if dependencies specified are appropriate)
- Try to get the package into one of gentoo's official repo

**Comment by jbuchermn** [comment]
That's great! (I used to run gentoo in the past, so I like that there's an ebuild now).

Release management isn't really strong in newm at the moment, basically I only work on master (+ sometimes a prerelease branch). So the stable versioned packages is not going to be that easy...

**Comment by x0rzavi** [comment]
Hi, looks like the [wayland-desktop](https://github.com/bsd-ac/wayland-desktop) overlay recently added newm and pywm, which is much better and structured, closing the issue :")
