### ISSUE TITLE
Include tray in panel

### ISSUE THREAD

**Issue by CRAG666** [jbuchermn/newm#14]
I want to use nm-applet and I wish I could have its tray-icon here, also for telegram and other applications that use it, I was also thinking that maybe it could be that waybar is supported that already has an implementation of this

**Comment by jbuchermn** [comment]
I think supporting waybar should be the way to go. I intend to rethink all panel functionality in v0.3 and get rid of the current bars, launcher, notifiers and lock screen.

**Comment by CRAG666** [comment]
That could be an option or have the option to delegate the task to a command, as sway does. Sway has its own bar but if you don't like it, it has the option of delegating the work to a command, in this case, waybar

**Comment by jbuchermn** [comment]
Does this work in waybar at the moment?

**Comment by CRAG666** [comment]
The command itself can be any bar e.g. waybar or i3bar-rs or any other

**Comment by CRAG666** [comment]
I can do this in newm, if so I haven't tried to do it yet, I don't know how to do it in the first place :(, if you have any idea I'll try it without problems

**Comment by CRAG666** [comment]
I just used waybar in newm and it works perfect, the detail is that the newm native bar overlaps waybar.

**Comment by CRAG666** [comment]
![waybar](https://i.ibb.co/hHqFCzD/screen-1637603334.png)

**Comment by CRAG666** [comment]
Run waybar from the console, this leads me to deduce that I can call waybar from the on_startup function, only the detail of the native bar would be left.
![waybar execute](https://i.ibb.co/vVHbRrn/screen-1637603426.png)

**Comment by jbuchermn** [comment]
Yeah exclusive zones are not respected so also tiled windows overlap waybar at the moment. L

Supporting exclusive zones is out of scope for v0.2 but I want to be able to use waybar instead of the default bar. That should be quite easy.

nm-applet works?

**Comment by CRAG666** [comment]
![swaybar](https://i.ibb.co/CHkqHL8/screen-1637603718.png)
swaywm makes this way the call of another bar different from the native one, I believe that something similar could be achieved in newm. As for nm-applet I have not been able to test it because the native bar is overlapped. but I consider that if it would work because it is something that waybar handles by itself. as for the windows overlapping way bar is a desired feature, because with Modpress you could see the bar and it does not take space.

Translated with www.DeepL.com/Translator (free version)

**Comment by CRAG666** [comment]
I just tested nm-applet and it does work, as I said it is something that waybar handles internally and that even swaywm has not been able to solve natively. As I said it's just a matter of removing the native overlay bar.

**Comment by CRAG666** [comment]
What is the status of this? @jbuchermn

**Comment by jbuchermn** [comment]
I'm going to add a config option to disable native bars and use a layer shell app instead. Then you should be able to use waybar without issue.

But I have a few bugs to fix that are higher priority. I'll keep this issue up to date

**Comment by CRAG666** [comment]
Thank you very much I look forward to this function

**Comment by jbuchermn** [comment]
I just pushed two commits that enable replacing native bar with waybar. Just disable the native one:

```
bar = { 'enabled': False }
```

and start waybar. After hitting Mod it should be visible.

A permanently visible top bar is currently not possible in newms layout - but it's in the backlog for v0.3

**Comment by CRAG666** [comment]
thanks
