### ISSUE TITLE
Is the developer planning to support newm on Xorg?

### ISSUE THREAD

**Issue by Darahaas2001** [jbuchermn/newm#141]
Hello , I seriously loved newm for its smoothness and dope transitions, knowing that wayland is not fully matured for the time being , does the developer have any intention to partially support it for Xorg (because nvidia + wayland = trouble).

**Comment by jbuchermn** [comment]
Nope, not from my part at least. I'm not going to do any work to keep xorg alive any longer.

The obivous way to go is fix NVidia on Wayland... (or, as the sway devs handle it, not buy NVidia hardware)
