### ISSUE TITLE
Input inhibitor request

### ISSUE THREAD

**Issue by jrens** [jbuchermn/newm#144]
Could I ask for a feature request to get the input inhibitor protocol working so we can swap for any of the waylocks please.

**Comment by jbuchermn** [comment]
https://wayland.app/protocols/wlr-input-inhibitor-unstable-v1 says this protovol is deprecated - is this true?

Anyway, supporting any such protocol should not be too difficult. Please open a feature request over on [pywm](https://github.com/jbuchermn/pywm) and name the proper protocol to go with :)

**Comment by jrens** [comment]
Ok opened https://github.com/jbuchermn/pywm/issues/18
