### ISSUE TITLE
Option to allow scrolling in unfocused windows

### ISSUE THREAD

**Issue by a-priestley** [jbuchermn/newm#145]
Hi there,
In newm, scrolling on a window focuses it, taking away the ability to action another window without re-focusing it fist.
In other DE's/WM's it's possible to hover over windows and scroll their contents while retaining the ability to type in another window.
Is this possible to implement in newm?

**Comment by jbuchermn** [comment]
I'm not quite sure how this would be made to work. Is this possible on sway? Can you point me to the relevant configuration?

**Comment by a-priestley** [comment]
I'm actually not sure about that one and I realize now that "other" De's/WM's I'm thinking of had been X11 based. Due to the isolating nature of wayland compositors it may not be possible without some script in the config.
Something like:
```
On Scroll
    If other window is focused
        wait 500ms
        focus last window
```
Shouldn't be too hard for me to figure out, but the question remains--is there something more native to be done to accomplish it?

**Comment by jbuchermn** [comment]
Closing this for now, as I think this goes a bit beyond a single compositors characteristic
