### ISSUE TITLE
Unlocking doesn't work correctly

### ISSUE THREAD

**Issue by anton-granzow** [jbuchermn/newm#147]
Hey,
when I lock newm using the default config of newm and then try to unlock it, I get a black screen. From there I can switch to TTY and back to get a mouse but nothing else, no shortcuts working. Starting newm form TTY and doing lock and unlock, I get thrown back into the TTY.
Got a Arch Linux AUR newm install on top of a KDE Plasma install, so I log into newm using SDDM.
[newm_log.txt](https://github.com/jbuchermn/newm/files/9402950/newm_log.txt)
[newm_panel_log.txt](https://github.com/jbuchermn/newm/files/9402965/newm_panel_log.txt)

**Comment by CRAG666** [comment]
It is not Newm error but of the Arch maintenance, I do not include all the dependencies, the best option it has is to check that has all installed

**Comment by anton-granzow** [comment]
Found the issue. I did some crap with my pam config files in the past, causing python-pam to crash.
