### ISSUE TITLE
No $DISPLAY environment variable

### ISSUE THREAD

**Issue by tak2hu** [jbuchermn/newm#152]
so I installed, copy paste the docs and ran newm just fine. Tho I have this problem when I tried to open brave, krita and other apps, it didn't work bcuz there's no $DISPLAY environment variable. 

I did try using sway and it does have a $DISPLAY env var.

here are my logs and config

logs: https://pastebin.com/j2evEXPj

config: https://pastebin.com/q7GzE6kj

I use tuigreet that starts these scripts: https://pastebin.com/RV4hkcCR

**Comment by tewkanz** [comment]
Your logs say you don't have xwayland (looks like it's an optional dependency). Can you install xwayland, then rebuild pywm and see if that fixes it?

**Comment by tak2hu** [comment]
turns out it's not `xwayland_enable = True` but `pywm = { 'xwayland_enable': True }` that's supposed to be in my config file
