### ISSUE TITLE
XWayland application options that create new windows always seem to create floating windows

### ISSUE THREAD

**Issue by tewkanz** [jbuchermn/newm#157]
When an application creates a new window, for example, when you click the new window option in Firefox, that window is always created as a floating window. Those windows, however, are new instances of the application and should create tiled windows.

**Comment by tewkanz** [comment]
Ah, my bad, this specifically is an issue for xwayland applications. For firefox specifically, the problem goes away if I set `MOZ_ENABLE_WAYLAND`.

**Comment by jbuchermn** [comment]
Closing as seems to be solved
