### ISSUE TITLE
gsettings specified in config aren't applied

### ISSUE THREAD

**Issue by yuval-benard** [jbuchermn/newm#158]
For example, modifying keyboard repeat rate and delay doesn't work, enabling/disabling touchpad natural scroll doesn't work.
If it matters, I am using Archcraft's version, which uses the default configuration provided by this github page. 
An image with my current settings is attached for reference.
![image](https://user-images.githubusercontent.com/82278433/192490723-fa323e31-a387-454a-a3a4-bdc3efef8505.png)

**Comment by CRAG666** [comment]
@yuval-benard  These configurations only apply to Gnome

**Comment by jbuchermn** [comment]
Thanks, @CRAG666 - indeed, gnome configuration is not read at any place. This should be possible by configuring libinput.
