### ISSUE TITLE
Add support wlr-gamma-control

### ISSUE THREAD

**Issue by CRAG666** [jbuchermn/newm#16]
I use wlsunset but it needs that library. wl sunset is to reduce eyestrain

**Comment by jbuchermn** [comment]
I'll look into that, should be possible

**Comment by CRAG666** [comment]
thanks

**Comment by jbuchermn** [comment]
https://github.com/jbuchermn/pywm/commit/8e640043ea42f35bb1e813d7949e931c59e70a8e
