### ISSUE TITLE
Opening applications from waybar does not work

### ISSUE THREAD

**Issue by AlexD97** [jbuchermn/newm#162]
When clicking on e.g. the volume indicator in waybar I want that pavucontrol opens. Instead, nothing opens visibly but the other applications slide under the waybar. In htop I can see that pavucontrol is open and if I kill it the applications that were partly under the waybar are now in place again.

**Comment by jbuchermn** [comment]
I can reproduce. This si something that used to work so I'm taking a look.

**Comment by AlexD97** [comment]
Now it's indeed working. 
Unfortunately, waybar needs now a lot of time to start. I suspect that's due to xdg-desktop-portal-wlr. `journalctl` gives me 
```
Portal service (wlroots implementation) was skipped because of a failed condition check (ConditionEnvironment=WAYLAND_DISPLAY).
```
Did you encounter the same behaviour? (I have copied my NixOS configuration mostly from yours.)

**Comment by jbuchermn** [comment]
I suspect this is unrelated. Indeed essbar sometimes takes a long time to start up, I've seen this as well.

**Comment by AlexD97** [comment]
Do you mean it's unrelated to your fix or unrelated to xdg-desktop-portal-wlr?

**Comment by jbuchermn** [comment]
Unrelated to the fix (and possibly the compositor as such) - Portal sounds like a reasonable explanation.
