### ISSUE TITLE
Switch language layout

### ISSUE THREAD

**Issue by EpsilonKu** [jbuchermn/newm#167]
How to switch language layout? I can't find any example or documentation((

**Comment by CRAG666** [comment]
Pleace read the doc, 
![imagen](https://user-images.githubusercontent.com/34254373/200991937-ec052d11-b233-469f-aa86-48e9e9036d05.png)

**Comment by EpsilonKu** [comment]
I want to set second layout and switch between them.

**Comment by CRAG666** [comment]
your need config xkb_options, this option has nothing to do with newm

**Comment by EpsilonKu** [comment]
Yeah, thanks. But will be good if it has this option. But seems like dev is busy right now.
