### ISSUE TITLE
Screen sharing do not work

### ISSUE THREAD

**Issue by CRAG666** [jbuchermn/newm#17]
I tried on all meeting platforms and the problem persists, I notice that the cursor does not change shape, when I share the screen in swaywm the cursor takes the shape of a cross, a behavior that does not occur in newm. I already tried the solutions that he gave me, but none seems to work I think that is not that problem, I have the theory that maybe it is in the mause events, today that I use it all day I notice that at times the cursor changes size. from being small to being extremely large.

**Comment by jbuchermn** [comment]
Can you point me to the apps you use for sharing, so I can try? Webrtc is working for me at the moment, haven't tried others.

Changing the cursors shape might be a feature of sway, but it's not something that happens automatically nor have I added it explicitly.

**Comment by jbuchermn** [comment]
However, I have to add.. it only works when I configure xdg-desktop-portal-wlr to use a fixed output. Possibly default configuration relies on the layer shell, as the output of running it without config suggests - see #8 for layer shell status

![share](https://user-images.githubusercontent.com/23573451/141450450-1266e3a3-24cc-4a27-ba14-2233f813f7c5.png)

**Comment by CRAG666** [comment]
I tested https://meet.jit.si/, google meet and microsoft teams.
I tried with the settings you gave me but they work, could you give me the exact command to test. I really want to make newm my default wm

**Comment by CRAG666** [comment]
I don't know if these errors are relevant
** (/usr/lib/xdg-desktop-portal:9674): WARNING **: 08:58:26.392: No skeleton to export
dbus-daemon[9515]: [session uid=1000 pid=9515] Activating service name='org.freedesktop.impl.portal.desktop.wlr' requested by ':1.10' (uid=1000 pid=9674 comm="/usr/lib/xdg-desktop-portal ")
2021/11/12 08:58:26 [ERROR] - config: no config file found
dbus-daemon[9515]: [session uid=1000 pid=9515] Successfully activated service 'org.freedesktop.impl.portal.desktop.wlr'
dbus-daemon[9515]: [session uid=1000 pid=9515] Successfully activated service 'org.freedesktop.portal.Desktop'
2021/11/12 08:59:32 [ERROR] - pipewire_loop_iterate failed: Error desconocido -1
2021/11/12 08:59:32 [ERROR] - pipewire_loop_iterate failed: Error desconocido -1
2021/11/12 08:59:32 [ERROR] - pipewire_loop_iterate failed: Error desconocido -1
2021/11/12 08:59:38 [ERROR] - pipewire_loop_iterate failed: Error desconocido -1
2021/11/12 08:59:38 [ERROR] - pipewire_loop_iterate failed: Error desconocido -1
2021/11/12 08:59:38 [ERROR] - pipewire_loop_iterate failed: Error desconocido -1
^C

**Comment by CRAG666** [comment]
run start-newm inside sway and opened a browser and shared screen in this way if you can share screen but the detail that I notice is that if the cursor changes shape, which running only start-newm does not happen, this makes my theory grow of the mause event, because it doesn't change shape

**Comment by CRAG666** [comment]
composer doesn't support zwlr_layer_shell_v1

It is the same error as with slurp and rofi, well how do I configure an output to use it temporarily in what implements a solution?

**Comment by jbuchermn** [comment]
Please check my screenshot above (and xdg-desktop-portal-wlr doc) in detail. The output you provide clearly states that xdg-desktop-portal-wlr is run without config file. This however appears to not be possible on a compositor which does not support layer shell. You need to start it by hand with the config from my screenshot.

**Comment by CRAG666** [comment]
Well I will do it while the final solution is implemented, thank you very much, I will continue to report bugs as I have done now.

**Comment by jbuchermn** [comment]
Thanks a lot, also for reporting all the bugs and missing features - this helps a lot!
