### ISSUE TITLE
How to change the color of panel lock?

### ISSUE THREAD

**Issue by DaMar4** [jbuchermn/newm#172]
hi everyone, how I can change color(background color and foregroundcolor) of this panel?

panels = {
    "lock": {
        "cmd": "alacritty -e newm-panel-basic lock",
        "w": 0.7,
        "h": 0.7,
        "corner_radius": 20,
    },

**Comment by DaMar4** [comment]
thanks a lot

**Comment by CRAG666** [comment]
@DaMar4 Pleace close issue
