### ISSUE TITLE
Newm blur not working. 

### ISSUE THREAD

**Issue by Teenarp2003** [jbuchermn/newm#173]
i found this issue opened in #136  but found no solution to it.. here is my config. can anyone help? 

float_apps = {"Blueman"}
common_rules = {"float":True, "float_size": (750, 750), "float_pos":(0.5, 0.35)}
blur_apps = {"rofi","waybar","alacritty","Kitty"}
def rules(view):
    if view.app_id in float_apps:
        return common_rules
    if view.app_id in blur_apps:
        return {"blur": {"radius": 6, "passes": 4}}
    return None

**Comment by sioonhho** [comment]
It doesn't explicitly say it in the documentation, but for blur to work you also need to enable opacity. I may put in a pr to update the documentation since the blur example could be a hair better.

The opacity setting in `alacritty.yml` doesn't seem do anything, here's a working example:
``` python
# config.py
...
def rules(view):
  if view.app_id == "Alacritty":
    return {
      'blur': { 'radius': 5, 'passes': 3 },
      'opacity': 0.8
    }
  return None

view = {
  'rules': rules
}
...
```

**Comment by Teenarp2003** [comment]
Thanks a lot @sioonhho
