### ISSUE TITLE
Newm window overlaps waybar 

### ISSUE THREAD

**Issue by Teenarp2003** [jbuchermn/newm#174]
The newm window is overlapping waybar on all modes.
 
(Waybar visible on zoomed out view ) 

However this problem does not happen with the default bar, which is visible on all modes except fullscreen.. 

I looked through the issues but could not find anything about it. Can anyone help?

**Comment by CRAG666** [comment]
![imagen](https://user-images.githubusercontent.com/34254373/208214763-39eae28c-5e30-447a-93b3-f4539addaac6.png)
@Teenarp2003  please check this, quit waybar onstarup

**Comment by Teenarp2003** [comment]
Thanks @CRAG666 
Fixed it

**Comment by CRAG666** [comment]
my config on kitty
![imagen](https://user-images.githubusercontent.com/34254373/208279342-ca4a728e-436e-486a-88a8-b269e539da36.png)
@Teenarp2003

**Comment by Teenarp2003** [comment]
Nice! I just found your post on unixporn😄
