### ISSUE TITLE
Core dumped

### ISSUE THREAD

**Issue by Laamaz** [jbuchermn/newm#176]
`~/.cache ~
~
newm - script dir is /usr/bin, log dir is /home/onni/.cache, arguments are -d
Aborted (core dumped)`

Getting this issue. I tried the fix of installing polkit. I installed newm using `yay -S newm-git`. I am using the latest version of EndeavourOS. Could that be the issue? I assume newm should work on it. Any help is appreciated.

**Comment by Ari-RERA-43** [comment]
How did you fix this?
