### ISSUE TITLE
Define applications as floating

### ISSUE THREAD

**Issue by CRAG666** [jbuchermn/newm#18]
There is a feature of swaywm that I miss, it is the ability to define applications as floating, for example pavucontrol or nwg-shell applications

**Comment by jbuchermn** [comment]
Yeah this sounds reasonable. Maybe I'll get around to adding it to v0.2

**Comment by CRAG666** [comment]
thanks

**Comment by jbuchermn** [comment]
Initial support is implemented: https://github.com/jbuchermn/newm/commit/d380610455afecdc6bfa02da859f60076de15920

**Comment by CRAG666** [comment]
It works very well
