### ISSUE TITLE
Custom Resolution

### ISSUE THREAD

**Issue by CRAG666** [jbuchermn/newm#19]
In swaywm I can define custom resolutions for example in sway I have my laptop monitor at 1920x1080 but newm only detects 1366x768, is there any way to achieve this in newm. I already tried all the settings and it doesn't seem to work

**Comment by jbuchermn** [comment]
Config concerning outputs has changed to v0.2, this isn't yet documented, as v0.2 is not released. See [config.py](https://github.com/jbuchermn/dotfiles/blob/master/newm/home/.config/newm/config.py) for an example

**Comment by CRAG666** [comment]
thanks

**Comment by CRAG666** [comment]
it works fine, you just can't define the same scale on two monitors

**Comment by jbuchermn** [comment]
What happens if you use the same scale?

**Comment by jbuchermn** [comment]
Are you sure, you want scale < 1? HiDPI monitors generally have scale = 2.

To understand that correctly: If you set same scale (0.7 and 0.7), monitors are black / blinking. If you set different scales (0.7 and 0.8), everything works as expected?

Switching by shortcuts is not implemented yet. It's one of the biggest missing features for v0.2

**Comment by CRAG666** [comment]
it doesn't work if they are equal in float type. With respect to <1, it's a matter of taste, personally things look very good at that size, in fact the captures are at that scale, I don't like gtk elements that are too large and with a large font size everything looks very well.

**Comment by jbuchermn** [comment]
what do you mean by "equal in float type"?

**Comment by CRAG666** [comment]
I mean 0.7 or any other number that is float

**Comment by jbuchermn** [comment]
So float scaling does not work, or does it not work, if both scales are floats and equal, or if both scales are float and inequal? Does it work if both scales are int and equal?

Can you state clearly, when problems arise?

**Comment by jbuchermn** [comment]
That's interesting.. can you try 0.7 and 0.7001 or something like that. What's happening then?

**Comment by CRAG666** [comment]
probare a si ahora reiniciar para aplicar los cambios que apenas realizo

**Comment by CRAG666** [comment]
![error](https://i.ibb.co/VjPF1fY/screen-1637003163.png)
this happens

**Comment by CRAG666** [comment]
This is a capture and the flicker is not seen but the flicker does occur and is constant

**Comment by jbuchermn** [comment]
Okay, I can't see the exact scales in the screenshot but I assume they're very close.

If I understand correctly, at 0.7 and 0.8 it works?

Is the flicker on both screens?

**Comment by CRAG666** [comment]
Works fine at 0.7, 0.8 but not at 0.7, 0.7

**Comment by jbuchermn** [comment]
Okay, I haven't been able to reproduce this yet.

Can you post two log files, one where it works (0.7 and 0.8) and one where it doesn't work (0.7 and 0.7)

**Comment by CRAG666** [comment]
How do I get the  log files?

**Comment by jbuchermn** [comment]
$HOME/.cache/newm_log

Diego Aguilar ***@***.***> schrieb am Di. 16. Nov. 2021 um
16:07:

**Comment by CRAG666** [comment]
Errors from xkbcomp are not fatal to the X server
00:09:37.133 [DEBUG] [xwayland/xwm.c:1583] unhandled X11 event: MappingNotify (34)
00:09:37.133 [DEBUG] [xwayland/xwm.c:1583] unhandled X11 event: MappingNotify (34)
[INFO] panel_launcher.py:51 2021-11-17 10:03:18: Subprocess for panel lock died
[INFO] panel_launcher.py:40 2021-11-17 10:03:18: Starting alacritty -e newm-panel-basic lock in None
[ERROR] panel_launcher.py:44 2021-11-17 10:03:18: Subprocess
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/newm/panel_launcher.py", line 49, in check
    raise Exception()
Exception

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/newm/panel_launcher.py", line 42, in _start
    self._proc = subprocess.Popen(cmd.split(" "), cwd=cwd)
  File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)

**Comment by jbuchermn** [comment]
The logs are truncated (right now newm and pywm are very chatty in debug mode) - could you possibly upload the files as attachments?

**Comment by CRAG666** [comment]
![newm_log](https://drive.google.com/file/d/1v4bQ7qwnDxY6XBssDA-QGoCtBMj7ypDD/view?usp=sharing)

**Comment by jbuchermn** [comment]
Thanks.

In the logs the scale is set to 0.7 and 0.8 - so if I understand correctly these settings work correctly? Can you post a log with 0.7 and 0.7 where the blinking occurs?

**Comment by CRAG666** [comment]
I'm doing it now, it's supposed to be the total history since I started using newm.

**Comment by CRAG666** [comment]
0.7 and 0.7 scale
[newm_log](https://drive.google.com/file/d/1JeGdxq_FK_A7h7BbNk-dDHFq9NZmYZjC/view?usp=sharing)

**Comment by CRAG666** [comment]
I deleted the previous log to have a cleaner one, it's the link I just posted.

**Comment by jbuchermn** [comment]
Thanks.

The issue appears to be in these lines:

> [DEBUG] pywm.py:270 2021-11-18 11:43:19:   Output(DP-2) with 1829x1463, scale 0.700000 at 0, 0
> [DEBUG] pywm.py:270 2021-11-18 11:43:19:   Output(eDP-1) with 1951x1097, scale 0.700000 at 1828, 0
> [DEBUG] layout.py:406 2021-11-18 11:43:19: Setup of newm workspaces
> [DEBUG] layout.py:408 2021-11-18 11:43:19:   Workspace[0] at 0, 0 --> 3779, 1463

What should be there is something like

> [DEBUG] pywm.py:270 2021-11-18 11:43:19:   Output(DP-2) with 1280x1024, scale 1.000000 at 0, 0
> [DEBUG] pywm.py:270 2021-11-18 11:43:19:   Output(eDP-1) with 1951x1097, scale 0.700000 at 1280, 0
> [DEBUG] layout.py:406 2021-11-18 11:43:19: Setup of newm workspaces
> [DEBUG] layout.py:408 2021-11-18 11:43:19:   Workspace[0] at 0, 0 --> 1280, 1024
> [DEBUG] layout.py:408 2021-11-18 11:43:19:   Workspace[1] at 1280, 0 --> 1951, 1097

Note the difference: First both outputs overlap, secondly they don't. There is some rounding error going on which I'll have to find (possibly this is even a wlroots thing, so might be hard).

Manually placing the outputs should work so long:

```
outputs = [
    { 'name': 'eDP-2', 'pos_x': 0, 'pos_y': 0, 'scale': 0.7},
    { 'name': 'eDP-1', 'pos_x': 1829,'pos_y': 0,'scale': 0.7}
]

```

**Comment by CRAG666** [comment]
outputs = [
    {'name': 'eDP-1', 'pos_x': 1830, 'pos_y': 0, 'scale': 0.7},
    {'name': 'DP-2', 'pos_x': 0, 'pos_y': 0, 'scale': 0.7},
]
This worked, now I don't know whether to close the issue or will you implement a way to make it automatic?

**Comment by jbuchermn** [comment]
Leave it open for now, it's a bug after all.

I'll take a look and close it if it can't be fixed

**Comment by CRAG666** [comment]
thanks, I can't stop saying it, even with bugs and all, newm is above other wayland based wm's in terms of look and feel and user experience.

**Comment by jbuchermn** [comment]
Thanks! I'm keen on getting most bugs out of the way for v0.2

I just pushed a fix to pywm. This should make the configuration superfluous.

**Comment by CRAG666** [comment]
excellent work, there are only floating windows left that keep popping up problems as you fix them. thanks
