### ISSUE TITLE
Customizable opening position and size float windows

### ISSUE THREAD

**Issue by CRAG666** [jbuchermn/newm#20]
The floating windows option works perfectly, now the problem arises that the floating windows are quite small, I would like to be able to configure the size and position of those floating windows when they open, I have this configuration in sway:

for_window [app_id="zenity"] floating enable
for_window [app_id="wdisplays"] floating enable
for_window [app_id="io.crow_translate.CrowTranslate"] floating enable
for_window [app_id="catapult"] floating enable; move up 400
for_window [app_id="pavucontrol"] floating enable, resize set width 40 ppt height 60 ppt
for_window [app_id="blueman-manager"] floating enable, resize set width 40 ppt height 60 ppt
I would like to be able to have it in newm.

I currently have this in newm:
``` python
def should_float(view):
    os.system(f'echo {view.app_id} >> app_id.txt')
    if view.app_id == "pavucontrol":
        return True
    if view.app_id == "blueman-manager":
        return True
    return None
```
but imagine something like:

``` python
def should_float(view):
    os.system(f'echo {view.app_id} >> app_id.txt')
    if view.app_id == "pavucontrol":
        width = 40 # ppt
        heigh = 60 # # ppt
        position = (400, 200) # px
        return True, width, heigh, position
    return None
```
but you could have a better implementation

**Comment by jbuchermn** [comment]
This looks like a good idea, I'll give it a try

**Comment by jbuchermn** [comment]
See https://github.com/jbuchermn/newm/commit/7469c98b2d88fee947a77cc60b11e78a8e6689ea

**Comment by CRAG666** [comment]
thanks

**Comment by CRAG666** [comment]
Si posiciona pero no cambia de tamaño, o tendrás un ejemplo de cómo lo probaste, porque lo probé y no funciona:
``` python
def should_float(view):
    size = (600, 600)
    position = (0.5, 0.2)
    os.system(f'echo {view.app_id} >> app_id.txt')
    if view.app_id == "pavucontrol":
        return True, size, position
    if view.app_id == "blueman-manager":
        return True, size, position
    return None
```

**Comment by CRAG666** [comment]
when opening it seems that it takes the given size but the size is not maintained

**Comment by jbuchermn** [comment]
Apps can change their size. This is not prevented on floating views. You can actually change the size yourself using Logo and two fingers.

Catapult e.g. would not be usable of footing windows were not allowed to change size.

**Comment by CRAG666** [comment]
ok, I understand resizing, only it is cumbersome to have to do it manually, I thought that defining it in the function was enough, if how to do it is swaywm

**Comment by jbuchermn** [comment]
You don't need to do it manually; you can set initial size in the config. This will be maintained until you either resize the window or it changes size (like e.g. catapult does when showing options).
