### ISSUE TITLE
mpv and imv are not visible

### ISSUE THREAD

**Issue by CRAG666** [jbuchermn/newm#21]
I am using newm v0.2 and apply the patches for wlroots that it told me, everything seems to work correctly, but when trying to see a video with mpv, mpv never becomes visible only the audio is heard, I try imv which is an image viewer the result is the same, in both cases you only see a space on the desktop as if you had the application but only the background is seen.

![3 windows see 2](https://i.ibb.co/jHb0PYs/screen-1636826433.png)
![mpv not found](https://i.ibb.co/6sqH8s4/screen-1636826442.png)

**Comment by jbuchermn** [comment]
Thanks for the report. That's a regression of a change I made recently. Should be fixed by [4dcff229](https://github.com/jbuchermn/pywm/commit/4dcff229dbd6dc28530b9495c42781fc10624ff5)

**Comment by CRAG666** [comment]
thanks, it's work
