### ISSUE TITLE
Unable to start newm in minimal Artix install

### ISSUE THREAD

**Issue by holesome** [jbuchermn/newm#22]
I'm not able to start newm with the command `start-newm` from TTY in a minimal Artix Linux installation on a ThinkPad X220.

This is the content of the `newm_log` log file:

```
[INFO] config.py:70 2021-11-14 13:48:57: Loading config at /usr/lib/python3.9/site-packages/newm/default_config.py
[DEBUG] pywm.py:89 2021-11-14 13:48:57: PyWM init
[WARNING] auth_backend.py:111 2021-11-14 13:48:57: Could not find greeter: greeter
[DEBUG] pywm.py:390 2021-11-14 13:48:57: PyWM run
Running PyWM...
00:00:00.000 [INFO] [libseat] [libseat/backend/seatd.c:80] Could not connect to socket /run/seatd.sock: No such file or directory
00:00:00.000 [INFO] [libseat] [libseat/libseat.c:76] Backend 'seatd' failed to open seat, skipping
00:00:00.003 [ERROR] [libseat] [libseat/backend/logind.c:310] Could not activate session: Permission denied
00:00:00.003 [INFO] [libseat] [libseat/libseat.c:76] Backend 'logind' failed to open seat, skipping
00:00:00.003 [ERROR] [libseat] [libseat/libseat.c:79] No backend was able to open a seat
00:00:00.003 [ERROR] [backend/session/session.c:84] Unable to create seat: Function not implemented
00:00:00.003 [ERROR] [backend/session/session.c:218] Failed to load session backend
00:00:00.003 [ERROR] [backend/backend.c:353] Failed to start a DRM session
python: ../src/wm/wm_server.c:177: wm_server_init: Assertion `server->wlr_backend' failed.
```
I installed newm through the AUR. As far as I know, all the dependencies listed in https://aur.archlinux.org/packages/newm-git/ are installed.

Am I missing something?

Thanks in advance.

**Comment by jbuchermn** [comment]
Hey,

installing from the AUR you should not  be missing anything, although I have not tested it on artix, only arch...

This looks like there is something missing in the wlroots backend startup. I had something like this in the past and needed to install seatd (see pywm README for a comment). Does sway start up without issue?

**Comment by holesome** [comment]
Hey,

Thanks for the quick reply. I have seatd installed. However, I noticed that wlroots wasn't installed yet. I don't know if that is required or not. wlroots got installed when I installed sway (see below) but even after that, I cannot start newm.

As for sway, I just installed it and I cannot run it either. I get a similar error when trying to run sway:
```
00:00:25.027 [ERROR] [wlr] [libseat] [libseat/backend/logind.c:310] Could not activate session: Method call timed out
00:00:25.027 [ERROR] [wlr] [libseat] [libseat/libseat.c:79] No backend was able to open a seat
00:00:25.027 [ERROR] [wlr] [backend/session/session.c:84] Unable to create seat: Function not implemented
00:00:25.027 [ERROR] [wlr] [backend/session/session.c:218] Failed to load session backend
00:00:25.027 [ERROR] [wlr] [backend/backend.c:353] Failed to start a DRM session
00:00:25.027 [ERROR] [sway/server.c:53] Unable to create backend
```
Do you know what could be the issue? It says that it wasn't able to open a seat, but why? I have seatd installed.

Thanks in advance for the help.

**Comment by holesome** [comment]
Nevermind. Both sway and newm work now. I guess there is some dependency missing in the AUR PKGBUILD? Potentially wlroots? Because I saw that wlroots was not yet installed before I installed sway. When I installed sway, wlroots got installed as a dependency of it and now both sway and newm work.

**Comment by jbuchermn** [comment]
You don't need wlroots as a dependency, newm (more precisely pywm) builds it from source and links it statically.

Since away didn't start up initially with the same error the issue probably is related to seats. I suppose seatd was not running.

Neither sway nor newm do rely on seatd, though. On a fresh arch install, wlroots can open a seat using systemd-logind.
