### ISSUE TITLE
Pinch to zoom wont work on firefox or evince

### ISSUE THREAD

**Issue by tsunekotakimoto** [jbuchermn/newm#26]
just trying this cool compositor, touchpad gestures work perfectly fine on the diferent views, but the gestures that are hardcoded in wayland apps like firefox or evince like pinch to zoom wont work.
thanks for the great job! looking forward for this wonderful project future!

**Comment by jbuchermn** [comment]
Thanks you for the nice words! These kind of gestures are handled via a Wayland protocol, which is not yet implemented in newm (all working gestures are handled on the Python side right now, not on c). Wayland gestures should not be too big a task to implement using wlroots, although I cannot quite tell, if there is going to be an interference with the python gestures. I'll give that a try on the v0.2 branch and keep you posted.

**Comment by jbuchermn** [comment]
I just added initial support to the v0.2 branch of pywm: https://github.com/jbuchermn/pywm/commit/42a712e35ece3c397f4309fa93412fb79d8b16ca

If you're interested in trying, be sure to also use v0.2 branch of newm

**Comment by CRAG666** [comment]
thanks
