### ISSUE TITLE
catapult does not display the options

### ISSUE THREAD

**Issue by CRAG666** [jbuchermn/newm#27]
Update newm today, and when trying to use catapult it does not show complete. Behavior that did not happen before
![catapult not work](https://i.ibb.co/Y3G4sgf/screen-1637246475.png)

**Comment by CRAG666** [comment]
This application does not work either (nwg-drawger) before this update it worked very well, it should be noted that both applications are wayland native. As I said before the update this worked perfectly
![other application error](https://i.ibb.co/KXKfxpC/screen-1637246966.png)

**Comment by jbuchermn** [comment]
I've noticed that as well. I'm doing some work at the moment on improving the opening of windows (have them map with proper size not configure afterwards). This is breaking some stuff, but I'm on it. 

Please keep on reporting issues when you encounter them.

**Comment by jbuchermn** [comment]
nwg-drawer appears to be unrelated. This actually ses layer shell (like slurp, waybar, ...) which does now start on newm, but isn't yet properly configured. So layer shell is not usable at this point.

**Comment by CRAG666** [comment]
I'll wait for it to be resolved so that I can use catapult again

**Comment by jbuchermn** [comment]
Just pushed a fix for catapult

**Comment by CRAG666** [comment]
?

**Comment by jbuchermn** [comment]
I just pushed the fix to make catapult work. You need to update both newm and pywm

**Comment by CRAG666** [comment]
thanks, but what about other applications that may be affected?

**Comment by jbuchermn** [comment]
nwg-drawer is unrelated as it uses layer shell. Layer Shell isn't properly supported right now. Probably it did work beforehand as the app defaulted to xdg-shell without layer shell available.

Are there other apps using xdg-shell with the issue?

**Comment by CRAG666** [comment]
I haven't noticed it yet, but there is an anomalous behavior when pop-up windows open, but I have already opened an issue about it.

**Comment by jbuchermn** [comment]
okay, closing this now, as we have the other issue
