### ISSUE TITLE
too big popup

### ISSUE THREAD

**Issue by CRAG666** [jbuchermn/newm#28]
I am testing applications, but when they open pop-up windows, the pop-up windows are huge, this behavior did not happen before, in the version before the error with catapult

**Comment by CRAG666** [comment]
![dbeaver](https://i.ibb.co/PzkvPRR/screen-1637274169.png)

**Comment by jbuchermn** [comment]
For example?

**Comment by CRAG666** [comment]
dbeaver, I try to create a new connection and the popup window is the size of the main window, which was not the case before.

**Comment by CRAG666** [comment]
what is in the image is the popup

**Comment by jbuchermn** [comment]
the image has very poor resolution, you can't really see anything.

I haven't got dbeaver installed, but I think it's a Java application. Can you check that it is actually wayland native?

Apart from that, I did change floating window sizing in general a bit. Earlier windows were always given there minimal size, which wasn't exactly nice to use. Now floating windows are allowed their default size.

**Comment by CRAG666** [comment]
ok, I see from what you tell me they work with the default size given by the application that opens it.

**Comment by CRAG666** [comment]
![open](https://i.postimg.cc/D0wntmLQ/screen-1637275345.png)

**Comment by CRAG666** [comment]
![native](https://i.postimg.cc/150bpyFs/screen-1637275340.png)
even though it is written in java the console tells me it is native in wayland

**Comment by CRAG666** [comment]
![popu](https://i.postimg.cc/Gp4MSR4B/screen-1637274168.png)
This is the image of the pop up. I don't know if it is related but now the screenshots are taken in very low quality, a behavior that didn't happen before. I also notice that the bad rendering of text that I mentioned in other issues is back.

**Comment by jbuchermn** [comment]
I think the text rendering (possibly screenshot issues, although this can depend on how you use grim) is related to your setting scale 0.7. If this happens on scale 1.0 or 2.0, please report another issue.

As far as popup sizes are concerned, it's probably a good idea to have it configurable - either default, like the client wants, or smallest size possible. I'll add that as an enhancement

**Comment by CRAG666** [comment]
thanks

**Comment by jbuchermn** [comment]
This is now default behaviour and can be configured via `view.floating_min_size`

As far as your screenshots are concerned - newm now has basic (not yet complete) layer shell support so you can use slurp to take screenshots of certain regions only. Maybe this improves issues.

**Comment by CRAG666** [comment]
thanks

**Comment by CRAG666** [comment]
view.floating_min_size what is the type? list, tuple or int

**Comment by jbuchermn** [comment]
it's a bool, when set to true newm will try to start floating windows sized minimally. This only works if windows report their min_width, min_height properly (not all do). If set to false newm will not try and change floating window sizing
