### ISSUE TITLE
the left-click menu appears too far from where you clicked

### ISSUE THREAD

**Issue by CRAG666** [jbuchermn/newm#29]
This behavior did not occur before today when trying to copy I noticed this behavior
![error](https://i.ibb.co/DWwrrvY/screen-1637422285.png)

**Comment by jbuchermn** [comment]
On which apps?

**Comment by CRAG666** [comment]
In all, probe thunar, electron applications and some gtk applications

**Comment by jbuchermn** [comment]
That‘s interesting.. can you post a log file?

**Comment by CRAG666** [comment]
[newm_log](https://drive.google.com/file/d/13PjSF4dlPRg0KOv7CpNcKcB5mMlovI8g/view?usp=sharing)

**Comment by CRAG666** [comment]
![error](https://i.ibb.co/j3yYvc6/screen-1637433641.png)
The same behavior is repeated when accessing the options menu in all applications

**Comment by jbuchermn** [comment]
That's really weird. In the log there are some warnings about layout / output stuff, maybe there's a bug. Could you post your output configuration?

**Comment by CRAG666** [comment]
outputs = [
    {'name': 'eDP-1', 'pos_x': 1833, 'pos_y': 0, 'scale': 0.7},
    {'name': 'DP-2', 'pos_x': 0, 'pos_y': 0, 'scale': 0.7},
]

**Comment by jbuchermn** [comment]
can you try commenting that out?

**Comment by CRAG666** [comment]
I already did it and everything works normally, however I would like to keep my configuration without something breaking

**Comment by CRAG666** [comment]
for example the scale, and the position was something that I put by the last issue where the monitors overlapped

**Comment by jbuchermn** [comment]
okay, yeah this is certainly a bug and I'm going to fix it, just trying to get more information. If you leave the scale, but set position to 0, 0 - does it work?

**Comment by CRAG666** [comment]
if it works well

**Comment by jbuchermn** [comment]
Okay thanks Im trying to reproduce this

**Comment by jbuchermn** [comment]
it was a pywm bug: https://github.com/jbuchermn/pywm/commit/c509564628a0cbfc70ceb48402060672daf7dba1

**Comment by CRAG666** [comment]
thanks
