### ISSUE TITLE
A wiki for setup

### ISSUE THREAD

**Issue by CRAG666** [jbuchermn/newm#3]
I love the visual aspect but heck, I don't know how to configure it, I don't really understand anything or how to navigate or change the window, I would like a wiki to be created where that is explained, in particular it is python but I don't know what options I have to configure , it would be good to have functions like the ones you have in swaywm even though to be honest your project is superior in terms of aesthetics

**Comment by CRAG666** [comment]
I understand everything, but how to configure the screen so that it has the appropriate size, because on my monitor the windows will open with an excessive size where I can not see the bottom of them

**Comment by jbuchermn** [comment]
The text size in apps is not controlled by any compositor. First you should check which apps use too big font sizes and change their config. What could possibly lead to very large windows (not just large fonts) is setting`output_scale` to 2 or higher if you do not have a HiDPI monitor. If you have e.g. a Full HD monitor, use `ouput_scale = 1.0` and `round_scale = 1.0`

**Comment by jbuchermn** [comment]
Thats quite okay, at this point testing the compositor and seeing at which points documentation is missing or unclear is a very important contribution. So I'm happy to answer all your questions and improve the docs while doing so. 

If you want to contribute, that's great to hear. Improving documentation is the most important aspect at the moment, as well as adding config possibilities that are missing.
