### ISSUE TITLE
how to use AltGr key

### ISSUE THREAD

**Issue by CRAG666** [jbuchermn/newm#30]
Como puedo usar esa tecla en newm en los shortcuts

**Comment by jbuchermn** [comment]
This was not supported. I just pushed a commit though that should make it possible by using "1", "2" or "3" instead of "M" in the keybinding. On my MacBook "3" is the right alt key.

**Comment by CRAG666** [comment]
ok, for example?

**Comment by jbuchermn** [comment]
"3-Enter"

**Comment by CRAG666** [comment]
thanks
