### ISSUE TITLE
Firefox floating windows are too large

### ISSUE THREAD

**Issue by CRAG666** [jbuchermn/newm#32]
![firefox](https://i.ibb.co/xswBg1t/screen-1637602493.png)
When the firefox audio dialog is displayed, it is too big and does not stay in the source window.

**Comment by jbuchermn** [comment]
I've noticed this as well. That window is somehow not recognized as floating and is tiled, which is wrong... However, this happens on sway as well - so I suspect it's a firefox issue

**Comment by jbuchermn** [comment]
See https://bugzilla.mozilla.org/show_bug.cgi?id=1628431

You can use

```
def should_float(view):
    if view.title.strip() == "Firefox - Sharing Indicator":
        return True, (100, 40), (0.5, 0.1)
```

**Comment by CRAG666** [comment]
thanks

**Comment by jbuchermn** [comment]
Closing as a firefox bug
