### ISSUE TITLE
Floating windows open in a different location

### ISSUE THREAD

**Issue by CRAG666** [jbuchermn/newm#33]
This behavior did not happen before, I am using the newest version of v0.2, then when I open pavucontrol whose window I have defined as floating it opens in a different place than the one it was called in the first place.
![oen pavucontrol](https://i.ibb.co/1n4qw7X/screen-1637677896.png)
![is open in other space](https://i.ibb.co/VpV4f81/screen-1637677918.png)

**Comment by CRAG666** [comment]
I opened it from edge and it opened in chrome, both in different workspaces.
``` python
def should_float(view):
    size = (700, 700)
    position = (0.5, 0.35)
    if view.app_id == "pavucontrol":
        return True, size, position
    if view.app_id == "blueman-manager":
        return True, size, position
    if view.app_id == "catapult":
        return True, (700, 700), (0.5, 0.1)
    return None
```

**Comment by jbuchermn** [comment]
So it opens at the position (0.5, 0.1) but on the wrong display?

**Comment by CRAG666** [comment]
Yes, that's exactly what happens. Everything else works fine

**Comment by jbuchermn** [comment]
Just tried to reproduce, but pavucontrol always opens on the same display where I start it from. Can you do some more tests - does it always happen in the same way? Maybe upload a log file.

**Comment by jbuchermn** [comment]
![20211124_17h02m12s_grim](https://user-images.githubusercontent.com/23573451/143273533-df96d003-3ba7-41be-9311-b674c4c06103.png)

**Comment by CRAG666** [comment]
This is already happening I think this new update solved it. Thank you. Hope to be able to use waybar soon and uninstall swaywm
