### ISSUE TITLE
How can I remove the lock screen

### ISSUE THREAD

**Issue by CRAG666** [jbuchermn/newm#34]
Every time newm is suspended, this window appears and it is not possible to close it
![newm](https://i.ibb.co/30V0fMG/screen-1637774932.png)

**Comment by jbuchermn** [comment]
What do you mean by suspend? Does unlocking work?

**Comment by jbuchermn** [comment]
You should be able to prevent automatic locking by giving only one power time

```
power_times = [120]
```

**Comment by jbuchermn** [comment]
Nevermind - I found an error in the positioning of this window. Please try again.

**Comment by CRAG666** [comment]
thanks

**Comment by jbuchermn** [comment]
Is it fixed?

**Comment by CRAG666** [comment]
now windows are not in place when unlocking
![before lock](https://i.ibb.co/Zfc508N/screen-1637783103.png)
![after lock](https://i.ibb.co/qrfqMyX/screen-1637783302.png)

**Comment by CRAG666** [comment]
the first image was before the lock and the other was after, and the windows are not in place

**Comment by jbuchermn** [comment]
This is unrelated.

It's expected behaviour if the monitor is unplugged and replugged. Possibly the monitor is reported as unplugged on hibernate or similar. Can you check that this consistently happens and then open a new issue including log?
