### ISSUE TITLE
I can't drag and drop the windows

### ISSUE THREAD

**Issue by CRAG666** [jbuchermn/newm#35]
After updating newm I can't drag and drop windows to accommodate them

**Comment by jbuchermn** [comment]
What do you mean by "drag and drop windows"? Like drag'n'drop files? Windows are tiled, they can't be dragged...

**Comment by CRAG666** [comment]
This occurs only when unlocked

**Comment by CRAG666** [comment]
Windows are tiled, they can't be dragged

**Comment by CRAG666** [comment]
I just restarted the computer then I noticed that this behavior only occurs after removing the newm lock screen.

**Comment by jbuchermn** [comment]
You mean floating windows? (As in `should_float`)

Only when clicking and dragging or also when moving by holding down `Logo`?

**Comment by CRAG666** [comment]
when pressing logo, as I said is a behavior that occurs right after you unlock the screen.

**Comment by jbuchermn** [comment]
Hmm I can't quite reproduce. Do you mean only immediatley after unlock, or once you unlock you're no longer able to move floating windows?

**Comment by CRAG666** [comment]
once unlock you're no longer able to move floating windows

**Comment by jbuchermn** [comment]
Can you upload a log?

**Comment by CRAG666** [comment]
I just noticed that it only happens on the secondary monitor

**Comment by jbuchermn** [comment]
Do you mean unlock via the lockscreen? 
![20211125_19h25m18s_grim](https://user-images.githubusercontent.com/23573451/143487958-29d7ecf8-f76b-4956-b898-eded0f93b667.png)

I cant' reproduce this. Is there any thing else which does not work after unlock? Only moving of floating windows seems a bit weird

**Comment by jbuchermn** [comment]
In the other issue you mention that a lockereren never appears. Can you clarify what's happening in this issue?

**Comment by CRAG666** [comment]
appeared at the bottom as in the first image, after updating it appeared, but when the windows were removed they could not be moved (rather I noticed that some touchpad events did not work) now the last update does not appear at all.

**Comment by CRAG666** [comment]
@jbuchermn  I would like to test if the problem no longer exists but as I said, the lockscreen does not appear.

**Comment by jbuchermn** [comment]
Let's focus on the other issue first. Once the lock screen appears, we can check back

**Comment by CRAG666** [comment]
Fixed the previous error this one was also solved
