### ISSUE TITLE
Alt-Tab function

### ISSUE THREAD

**Issue by CRAG666** [jbuchermn/newm#37]
This would be a very useful feature that I would like to have in newm, pressing Alt-Tab to cycle through currently open applications, as Windows, Mac or Linux does on other desktops, it is a feature that not even swaywm has.

**Comment by jbuchermn** [comment]
This is possibly via configuration right now, but I'm going to add a convenience function to layout to make it easier. I think it's a handy addition.

**Comment by CRAG666** [comment]
Currently how could I do it?

**Comment by jbuchermn** [comment]
If you want to try it yourself, check the `layout.py` file - however it's probably very hard until this class is documented better.

Anyway - You can now use the method `layout.move_next_view()` in a shortcut.
