### ISSUE TITLE
The cursor does not change position with layout.move_workspace()

### ISSUE THREAD

**Issue by CRAG666** [jbuchermn/newm#39]
the function does work, however the cursor does not move

**Comment by CRAG666** [comment]
when you change applications on any linux desktop the cursor does too. This happens in gnome, kde etc.

**Comment by jbuchermn** [comment]
You mean the cursor moves, when you focus another window (e.g. through alt-tab)? I've never seen that and I'd be very surprised if gnome or kde have that as default behaviour. Maybe I'll install one to check...

**Comment by jbuchermn** [comment]
I actually just checked on a vm using Gnome. This does not happen - when changing applications, the cursor stays fixed

**Comment by CRAG666** [comment]
Of course, if you test it with a single monitor, that behavior happens, maybe I won't explain it well. when there are two monitors the cursor stays in its position but now if it is moved to the other monitor the cursor does too

**Comment by CRAG666** [comment]
It is not that the cursor moves between X and Y it only goes to the other monitor when a window is focused on that monitor

**Comment by jbuchermn** [comment]
Maybe I understand what you mean. The cursor stays on the same position inside the monitor but moves to the other monitor?

I still find this very intuitive, especially in a Setup where Focus follows mouse, as in newm. The window focused after the shortcut would be determined by pointing on the other screen beforehand..

Anyway the pywm issue should, once resolved, make it quite easy to implement that in config.py 

Im closing this issue so long.
