### ISSUE TITLE
layout.move_next() view only moves in a workspace

### ISSUE THREAD

**Issue by CRAG666** [jbuchermn/newm#40]
This works, the problem is that it only cycles through single monitor apps, not all currently open apps. I would like to have something like what you did with ModPress, include the option of only_active_workspace = True

**Comment by jbuchermn** [comment]
This is now configurable (see `layout.py`)

**Comment by CRAG666** [comment]
You mean that I have to modify the code?

**Comment by jbuchermn** [comment]
No need to modify the code, but the layout-functions are not documented, so you need to check the file to see the options.

**Comment by CRAG666** [comment]
ok
``` python
def move_next_view(self, dv: int=1) -> None:
        views = self.views(self.get_active_workspace())
        focused_view = self.find_focused_view()

        if focused_view is not None and focused_view in views:
            idx = views.index(focused_view)
            next_view = views[(idx + dv)%len(views)]
            self.focus_view(next_view)
        elif len(views) > 0:
            self.focus_view(views[0])
```
I guess what you mean is that it rewrites the method within my configuration with my logic?

**Comment by jbuchermn** [comment]
I think you're one commit too early - I actually just pushed a couple of minutes ago. Sorry for that - The current one has more options.

Apart from that, if you need more specific logic in these functions it's a good starting place to copy them to your config.py and try.

**Comment by CRAG666** [comment]
Thank you, and an apology for being so picky. I will verify this again, I will be reporting each bug as before. Greetings

**Comment by jbuchermn** [comment]
That‘s Great to hear. Actually I'm not quite sure..

Probably a PR on the README.md?

**Comment by CRAG666** [comment]
Tenia pensado algo como la wiki pero podria comenzar por ahi, este fin de semana le dedico full time a esto

**Comment by jbuchermn** [comment]
Thanks for your contribution - keep it coming :)

Closing the issue now, as it's fixed.
