### ISSUE TITLE
Unable to find dependecies : python-imageio

### ISSUE THREAD

**Issue by plagache** [jbuchermn/newm#43]
Hi,

I am currently trying to use newm, but i am unable to complete the command "makepkg -si"

I encountered this error :
```
[0] makepkg -si                

==> Making package: newm-git 0.1.r27.g33aea1f.a6d799f-1 (dim. 05 déc. 2021 16:11:55)

==> Checking runtime dependencies...

==> Installing missing dependencies...

error: target not found: python-imageio

==> ERROR: 'pacman' failed to install missing dependencies.

==> Missing dependencies:

  -> python-imageio

==> Checking buildtime dependencies...

==> ERROR: Could not resolve all dependencies.

```

for the other dependecies like numpy I did : sudo pacman -S python-numpy

does anyone have the same error ? 

I am on artix openrc. 

thanks in advance.

**Comment by jbuchermn** [comment]
You need to install the dependency (check the AUR documentation).

The easiest way to do that is using an AUR helper: https://wiki.archlinux.org/title/AUR_helpers

**Comment by plagache** [comment]
Thank you,

It worked perfctly with yay.
