### ISSUE TITLE
waybar does not work

### ISSUE THREAD

**Issue by CRAG666** [jbuchermn/newm#44]
After updating the new changes of newm v2, I noticed that waybar is not showing, at first I thought that it just did not start, after checking my configuration I realized that everything was fine however when doing a htop and filtering the waybar name Note that if it was started but not shown, kill the process and start again waybar is shown, then the conclusion I reached that after updating something, it changes that it does not allow waybar to start as it did before.

**Comment by jbuchermn** [comment]
I noticed this bug too, but not consistently, only occasionally. Can you post the output of `newm-cmd debug` when waybar runs but is not shown?

**Comment by CRAG666** [comment]
<Layout {'xkb_layout': 'es', 'xkb_options': 'caps:swapescape', 'encourage_csd': False, 'debug_f1': True, 'xcursor_theme': 'Sweet-cursors', 'xcursor_size': 12, 'focus_follows_mouse': True, 'contstrain_popups_to_toplevel': True, 'enable_xwayland': True, 'outputs': [{'name': 'eDP-1', 'pos_x': 1833, 'pos_y': 0, 'scale': 0.7}, {'name': 'DP-2', 'pos_x': 0, 'pos_y': 0, 'scale': 0.7}], 'debug': False}>
  <LayoutState {'launcher_perc': 0, 'lock_perc': 0, 'final': False, 'background_opacity': 1.0}>

Workspace[1] at 0, 0 --> 1828, 1462
      <WorkspaceState {'_ws': <newm.layout.Workspace object at 0x7f2f500ff7c0>, 'i': 0, 'j': 0, 'size': 1, 'size_origin': None, 'intermediate_rows': [], 'intermediate_cols': [], 'state_before_fullscreen': None, 'top_bar_dy': 0, 'bottom_bar_dy': 0, 'state_before_overview': None}>
Workspace[0] at 1833, 0 --> 1951, 1097
      <WorkspaceState {'_ws': <newm.layout.Workspace object at 0x7f2f542ff700>, 'i': 0, 'j': 0, 'size': 1, 'size_origin': None, 'intermediate_rows': [], 'intermediate_cols': [], 'state_before_fullscreen': None, 'top_bar_dy': 0, 'bottom_bar_dy': 0, 'state_before_overview': None}>
 1: <View 1 (root): kitty, kitty, toplevel, 1252, xwayland=False, floating=False, focused=False, panel=lock, layer_panel=None> on workspace 1
      <ViewState {'is_tiled': False, 'is_layer': True, 'i': 0, 'j': 0, 'w': 0, 'h': 0, 'stack_data': (-1, 0, 1), 'stack_idx': 0, 'move_origin': None, 'scale_origin': None, 'float_pos': (0, 0), 'float_size': (0, 0), 'layer_initial': False}>
 2: <View 2 (root): Layer Shell, waybar, layer, 1332, xwayland=False, floating=True, focused=False, panel=None, layer_panel=bottom_bar> on workspace 1
      <ViewState {'is_tiled': False, 'is_layer': True, 'i': 0, 'j': 0, 'w': 0, 'h': 0, 'stack_data': (-1, 0, 1), 'stack_idx': 0, 'move_origin': None, 'scale_origin': None, 'float_pos': (0, 0), 'float_size': (0, 0), 'layer_initial': False}>
 3: <View 3 (root): Layer Shell, waybar, layer, 1332, xwayland=False, floating=True, focused=False, panel=None, layer_panel=bottom_bar> on workspace 0
      <ViewState {'is_tiled': False, 'is_layer': True, 'i': 0, 'j': 0, 'w': 0, 'h': 0, 'stack_data': (-1, 0, 1), 'stack_idx': 0, 'move_origin': None, 'scale_origin': None, 'float_pos': (0, 0), 'float_size': (0, 0), 'layer_initial': False}>
 4: <View 4 (root): ~, kitty, toplevel, 2195, xwayland=False, floating=False, focused=True, panel=None, layer_panel=None> on workspace 1
      <ViewState {'is_tiled': True, 'is_layer': False, 'i': 0, 'j': 0, 'w': 1, 'h': 1, 'stack_data': (0, 0, 1), 'stack_idx': 4, 'move_origin': None, 'scale_origin': None, 'float_pos': (0, 0), 'float_size': (0, 0), 'layer_initial': False}>
 6: <View 6 (root): Nuevo número · jbuchermn / newm - Google Chrome, google-chrome, toplevel, 3615, xwayland=False, floating=False, focused=False, panel=None, layer_panel=None> on workspace 0
      <ViewState {'is_tiled': True, 'is_layer': False, 'i': 0, 'j': 0, 'w': 1, 'h': 1, 'stack_data': (0, 0, 1), 'stack_idx': 6, 'move_origin': None, 'scale_origin': None, 'float_pos': (0, 0), 'float_size': (0, 0), 'layer_initial': False}>

**Comment by jbuchermn** [comment]
Do you get these in the log

```
[WARNING] view.py:312 ...: Cannot place layer view without fixed output
```

I think there's the bug - I'll keep on looking. Unfortunately I only get the error once in 10 or so tries.

**Comment by jbuchermn** [comment]
I just pushed an update - can you check if this changes anything in waybar behaviour?

**Comment by CRAG666** [comment]
The error still persists

**Comment by jbuchermn** [comment]
I can't reproduce anymore. Can you post a log?
