### ISSUE TITLE
Flickering in some regions of the screen

### ISSUE THREAD

**Issue by CRAG666** [jbuchermn/newm#47]
Before v0.2 joined with master this behavior did not occur. Now sometimes some of the regions of the screen flicker constantly, this happens for a while then stops and then at some point it happens again

**Comment by jbuchermn** [comment]
That‘s not possible, v0.2 is the same as master now. Nothing was changed on merge.

If you provide a more specific description on since when this  happens, I can take a look.

**Comment by CRAG666** [comment]
Well I noticed yesterday, but I think my statement was a bit random because it did not happen before. Anyway, the detail is not more than in some regions blinks occur that take 30 s to a minute then they do not happen again until after a while

**Comment by CRAG666** [comment]
It is a bit difficult to test because as I say it does not happen frequently or at least not with a frequency to monitor it, but it does happen. I realized because I have 2 jobs so I spend many hours in front of the computer it was in all that time that the error occurred 7 times throughout the day

**Comment by jbuchermn** [comment]
Okay, but this cannot happen only since the merge. Has it been happening for a longer time? Which apps do you use when it occurs?

**Comment by CRAG666** [comment]
I only use 3 applications during my day and they are kitty, dbeaver and some electron browser

**Comment by jbuchermn** [comment]
Ok. You don't use waybar, rofi, ...?

**Comment by CRAG666** [comment]
If I use waybar and rofi together with the previous applications but now that you mention it if you see that flicker where is waybar, in terms of browser I use chrome, edge and firefox.

**Comment by jbuchermn** [comment]
Does it happen after you open any menus or tooltips, .. on waybar? Or does it happen where the actual bar is?

**Comment by CRAG666** [comment]
Exactly now that we are opening up this is happening. It is exactly where the waybar is. for now it only happens on my second monitor

**Comment by jbuchermn** [comment]
Okay That‘s very helpful. Probably another bug related to output coordinates.

**Comment by CRAG666** [comment]
I will report anything new related to this problem.

**Comment by jbuchermn** [comment]
Haven't been able to reproduce this yet. So I think I need some more information...

**Comment by CRAG666** [comment]
I will close this for now, so far it has not happened except that waybar does not disappear completely, I hope the waybar is solved. If it happens again I will try to test for a longer time

**Comment by jbuchermn** [comment]
Does waybar still not disappear completely?

**Comment by jbuchermn** [comment]
Can you hit F1 while waybar is partly visible and search the log for

```
---- server begin ----
[...]
---- server end ------
```

**Comment by CRAG666** [comment]
> Does waybar still not disappear completely?

Not yet

**Comment by CRAG666** [comment]
> Can you hit F1 while waybar is partly visible and search the log for
> 
> ```
> ---- server begin ----
> [...]
> ---- server end ------
> ```

---- server begin ----
wm_layout
  wm_output: DP-2 (1280 x 1024) at 0, 0
  wm_output: eDP-1 (1366 x 768) at 1833, 0
wm_widget (3784.000000, 1097.000000 - 0.000000, 0.000000)
wm_widget (3784.000000, 0.000000 - 0.000000, 0.000000)
wm_widget (1833.000000, 1097.000000 - 0.000000, 0.000000)
wm_widget (1833.000000, 0.000000 - 0.000000, 0.000000)
wm_widget (1828.000000, 1462.000000 - 0.000000, 0.000000)
wm_widget (1828.000000, 0.000000 - 0.000000, 0.000000)
wm_widget (0.000000, 1462.000000 - 0.000000, 0.000000)
wm_widget (0.000000, 0.000000 - 0.000000, 0.000000)
wm_view: kitty, kitty, toplevel, 3258 (548.500000, 1900.500000 - 731.000000, 585.000000) of size 1816, 1450 (offset = 0, 0)
  surface (0, 0 constrained) of size 1816, 1450: 0x5597cab1d320
  wm_view_xdg for 0x5597cab1d320
wm_view: ~/.cache, kitty, toplevel, 5421 (613.500000, 491.500000 - 601.000000, 479.000000) of size 1816, 1450 (offset = 0, 0)
  surface (0, 0 constrained) of size 1816, 1450: 0x5597cab2d680
  wm_view_xdg for 0x5597cab2d680
wm_view: Flickering in some regions of the screen · Issue #47 · jbuchermn/newm - Google Chrome, google-chrome, toplevel, 6986 (1839.000000, 6.000000 - 1939.000000, 1085.000000) of size 1939, 1085 (offset = 0, 0)
  surface (0, 0 constrained) of size 1939, 1085: 0x5597cab42930
  wm_view_xdg for 0x5597cab42930
wm_view: Layer Shell, waybar, layer, 3295 (1833.000000, 1101.000000 - 1951.000000, 20.000000) of size 1951, 20 (offset = 0, 0)
  surface (0, 0) of size 1951, 20: 0x5597cab23aa0
  wm_view_layer for 0x5597cab23aa0 on output 0x5597c99822d0
wm_view: Layer Shell, waybar, layer, 3295 (0.000000, 1442.000000 - 1828.000000, 20.000000) of size 1828, 20 (offset = 0, 0)
  surface (0, 0) of size 1828, 20: 0x5597cab22fa0
  wm_view_layer for 0x5597cab22fa0 on output 0x5597c9ac3f60
wm_widget (1832.785698, -0.071438 - 1951.428605, 1097.142876)
wm_widget (-385.285736, 0.285702 - 2598.571473, 1461.428596)
---- server end ------

**Comment by CRAG666** [comment]
These are the records that he asked me

**Comment by CRAG666** [comment]
---- server begin ----
wm_layout
  wm_output: DP-2 (1280 x 1024) at 0, 0
  wm_output: eDP-1 (1366 x 768) at 1833, 0
wm_widget (3784.000000, 1097.000000 - 0.000000, 0.000000)
wm_widget (3784.000000, 0.000000 - 0.000000, 0.000000)
wm_widget (1833.000000, 1097.000000 - 0.000000, 0.000000)
wm_widget (1833.000000, 0.000000 - 0.000000, 0.000000)
wm_widget (1828.000000, 1462.000000 - 0.000000, 0.000000)
wm_widget (1828.000000, 0.000000 - 0.000000, 0.000000)
wm_widget (0.000000, 1462.000000 - 0.000000, 0.000000)
wm_widget (0.000000, 0.000000 - 0.000000, 0.000000)
wm_view: kitty, kitty, toplevel, 3258 (548.500000, 1900.500000 - 731.000000, 585.000000) of size 1816, 1450 (offset = 0, 0)
  surface (0, 0 constrained) of size 1816, 1450: 0x5597cab1d320
  wm_view_xdg for 0x5597cab1d320
wm_view: newm_log (~/.cache) - NVIM, kitty, toplevel, 5421 (613.500000, 491.500000 - 601.000000, 479.000000) of size 1816, 1450 (offset = 0, 0)
  surface (0, 0 constrained) of size 1816, 1450: 0x5597cab2d680
  wm_view_xdg for 0x5597cab2d680
wm_view: obs-studio no se puede usar dentro de neem · Número 49 · jbuchermn / newm - Google Chrome, google-chrome, toplevel, 6986 (1839.000000, 6.000000 - 1939.000000, 1085.000000) of size 1939, 1085 (offset = 0, 0)
  surface (0, 0 constrained) of size 1939, 1085: 0x5597cab42930
  wm_view_xdg for 0x5597cab42930
wm_view: Layer Shell, waybar, layer, 3295 (1833.000000, 1101.000000 - 1951.000000, 20.000000) of size 1951, 20 (offset = 0, 0)
  surface (0, 0) of size 1951, 20: 0x5597cab23aa0
  wm_view_layer for 0x5597cab23aa0 on output 0x5597c99822d0
wm_view: Layer Shell, waybar, layer, 3295 (0.000000, 1442.000000 - 1828.000000, 20.000000) of size 1828, 20 (offset = 0, 0)
  surface (0, 0) of size 1828, 20: 0x5597cab22fa0
  wm_view_layer for 0x5597cab22fa0 on output 0x5597c9ac3f60
wm_widget (1832.785698, -0.071438 - 1951.428605, 1097.142876)
wm_widget (-385.285736, 0.285702 - 2598.571473, 1461.428596)
---- server end ------

**Comment by jbuchermn** [comment]
These look like you are in overview state, where waybar is actually supposed to be visible?

Also, these logs don't look like you are on the most recent commit. Can you please update beforehand.

**Comment by CRAG666** [comment]
![waybar](https://i.ibb.co/542JsYy/screen-1639342634.png)
It is supposed to disappear completely but this does not happen there are still traces of waybar

**Comment by jbuchermn** [comment]
yep but your logs do not help if you take them at a point where waybar should be (and is) visible.

**Comment by jbuchermn** [comment]
Also.. I think these are damaging issues related to the backgrround... could you please (additionally to updating newm and pywm) set output scale to 1.0?

**Comment by CRAG666** [comment]
This is a record when waybar is not visible
---- server begin ----
wm_layout
  wm_output: DP-2 (1280 x 1024) at 0, 0
  wm_output: eDP-1 (1366 x 768) at 1833, 0
wm_widget (3784.000000, 1097.000000 - 0.000000, 0.000000)
wm_widget (3784.000000, 0.000000 - 0.000000, 0.000000)
wm_widget (1833.000000, 1097.000000 - 0.000000, 0.000000)
wm_widget (1833.000000, 0.000000 - 0.000000, 0.000000)
wm_widget (1828.000000, 1462.000000 - 0.000000, 0.000000)
wm_widget (1828.000000, 0.000000 - 0.000000, 0.000000)
wm_widget (0.000000, 1462.000000 - 0.000000, 0.000000)
wm_widget (0.000000, 0.000000 - 0.000000, 0.000000)
wm_view: kitty, kitty, toplevel, 3258 (548.500000, 1900.500000 - 731.000000, 585.000000) of size 1816, 1450 (offset = 0, 0)
  surface (0, 0 constrained) of size 1816, 1450: 0x5597cab1d320
  wm_view_xdg for 0x5597cab1d320
wm_view: newm_log (~/.cache) - NVIM, kitty, toplevel, 5421 (6.000000, 6.000000 - 1816.000000, 1450.000000) of size 1816, 1450 (offset = 0, 0)
  surface (0, 0 constrained) of size 1816, 1450: 0x5597cab2d680
  wm_view_xdg for 0x5597cab2d680
wm_view: Parpadeo en algunas regiones de la pantalla · Número 47 · jbuchermn / newm - Google Chrome, google-chrome, toplevel, 6986 (1839.000000, 6.000000 - 1939.000000, 1085.000000) of size 1939, 1085 (offset = 0, 0)
  surface (0, 0 constrained) of size 1939, 1085: 0x5597cab42930
  wm_view_xdg for 0x5597cab42930
wm_view: Layer Shell, waybar, layer, 3295 (0.000000, 1466.000000 - 1828.000000, 20.000000) of size 1828, 20 (offset = 0, 0)
  surface (0, 0) of size 1828, 20: 0x5597cab22fa0
  wm_view_layer for 0x5597cab22fa0 on output 0x5597c9ac3f60
wm_view: Layer Shell, waybar, layer, 3295 (1833.000000, 1101.000000 - 1951.000000, 20.000000) of size 1951, 20 (offset = 0, 0)
  surface (0, 0) of size 1951, 20: 0x5597cab23aa0
  wm_view_layer for 0x5597cab23aa0 on output 0x5597c99822d0
wm_widget (1832.785698, -0.071438 - 1951.428605, 1097.142876)
wm_widget (-385.285736, 0.285702 - 2598.571473, 1461.428596)
---- server end ------

**Comment by CRAG666** [comment]
When waybar is visible
---- server begin ----
wm_layout
  wm_output: DP-2 (1280 x 1024) at 0, 0
  wm_output: eDP-1 (1366 x 768) at 1833, 0
wm_widget (3784.000000, 1097.000000 - 0.000000, 0.000000)
wm_widget (3784.000000, 0.000000 - 0.000000, 0.000000)
wm_widget (1833.000000, 1097.000000 - 0.000000, 0.000000)
wm_widget (1833.000000, 0.000000 - 0.000000, 0.000000)
wm_widget (1828.000000, 1462.000000 - 0.000000, 0.000000)
wm_widget (1828.000000, 0.000000 - 0.000000, 0.000000)
wm_widget (0.000000, 1462.000000 - 0.000000, 0.000000)
wm_widget (0.000000, 0.000000 - 0.000000, 0.000000)
wm_view: kitty, kitty, toplevel, 3258 (548.500000, 1900.500000 - 731.000000, 585.000000) of size 1816, 1450 (offset = 0, 0)
  surface (0, 0 constrained) of size 1816, 1450: 0x5597cab1d320
  wm_view_xdg for 0x5597cab1d320
wm_view: newm_log (~/.cache) - NVIM, kitty, toplevel, 5421 (613.500000, 491.500000 - 601.000000, 479.000000) of size 1816, 1450 (offset = 0, 0)
  surface (0, 0 constrained) of size 1816, 1450: 0x5597cab2d680
  wm_view_xdg for 0x5597cab2d680
wm_view: obs-studio no se puede usar dentro de neem · Número 49 · jbuchermn / newm - Google Chrome, google-chrome, toplevel, 6986 (1839.000000, 6.000000 - 1939.000000, 1085.000000) of size 1939, 1085 (offset = 0, 0)
  surface (0, 0 constrained) of size 1939, 1085: 0x5597cab42930
  wm_view_xdg for 0x5597cab42930
wm_view: Layer Shell, waybar, layer, 3295 (1833.000000, 1101.000000 - 1951.000000, 20.000000) of size 1951, 20 (offset = 0, 0)
  surface (0, 0) of size 1951, 20: 0x5597cab23aa0
  wm_view_layer for 0x5597cab23aa0 on output 0x5597c99822d0
wm_view: Layer Shell, waybar, layer, 3295 (0.000000, 1442.000000 - 1828.000000, 20.000000) of size 1828, 20 (offset = 0, 0)
  surface (0, 0) of size 1828, 20: 0x5597cab22fa0
  wm_view_layer for 0x5597cab22fa0 on output 0x5597c9ac3f60
wm_widget (1832.785698, -0.071438 - 1951.428605, 1097.142876)
wm_widget (-385.285736, 0.285702 - 2598.571473, 1461.428596)
---- server end ------

**Comment by CRAG666** [comment]
> Also.. I think these are damaging issues related to the backgrround... could you please (additionally to updating newm and pywm) set output scale to 1.0 and check as well?

Sure in a moment I do

**Comment by CRAG666** [comment]
This does not happen if the scale is 1 but now I notice that if this happens when the scale is fractional

**Comment by CRAG666** [comment]
When the scale is less than 1 waybar it does not disappear completely

**Comment by jbuchermn** [comment]
This only happens on scales leading fractional pixel sizes, not fractional scales, i.e. the height in your config is 1024 / 0.7 = 1462.85...; 0.85 pixels can never be handled properly.

But in this case it can probably be mitigated - if you update and post a log where waybar is visible but shouldn't be visible, I can check.

**Comment by CRAG666** [comment]
---- server begin ----
wm_layout
  wm_output: DP-2 (1280 x 1024) at 0, 0
  wm_output: eDP-1 (1366 x 768) at 1828, 0
wm_widget (3779.000000, 1097.000000 - 0.000000, 0.000000)
wm_widget (3779.000000, 0.000000 - 0.000000, 0.000000)
wm_widget (1828.000000, 1097.000000 - 0.000000, 0.000000)
wm_widget (1828.000000, 0.000000 - 0.000000, 0.000000)
wm_widget (1828.000000, 1462.000000 - 0.000000, 0.000000)
wm_widget (1828.000000, 0.000000 - 0.000000, 0.000000)
wm_widget (0.000000, 1462.000000 - 0.000000, 0.000000)
wm_widget (0.000000, 0.000000 - 0.000000, 0.000000)
wm_view: kitty, kitty, toplevel, 3258 (548.500000, 1900.500000 - 731.000000, 585.000000) of size 853, 682 (offset = 0, 0)
  surface (0, 0 constrained) of size 1816, 1450: 0x5597cab1d320
  wm_view_xdg for 0x5597cab1d320
wm_view: ~, kitty, toplevel, 123543 (917.000000, 551.000000 - 451.000000, 360.000000) of size 1816, 1450 (offset = 0, 0)
  surface (0, 0 constrained) of size 1816, 1450: 0x5597c985ab30
  wm_view_xdg for 0x5597c985ab30
wm_view: newm_log (~/.cache) - NVIM, kitty, toplevel, 5421 (460.000000, 551.000000 - 451.000000, 360.000000) of size 1816, 1450 (offset = 0, 0)
  surface (0, 0 constrained) of size 1816, 1450: 0x5597cab2d680
  wm_view_xdg for 0x5597cab2d680
wm_view: Parpadeo en algunas regiones de la pantalla · Número 47 · jbuchermn / newm - Google Chrome, google-chrome, toplevel, 6986 (1834.000000, 6.000000 - 1939.000000, 1085.000000) of size 1939, 1085 (offset = 0, 0)
  surface (0, 0 constrained) of size 1939, 1085: 0x5597cab42930
  wm_view_xdg for 0x5597cab42930
wm_view: Layer Shell, waybar, layer, 3295 (0.000000, 1442.000000 - 1828.000000, 20.000000) of size 1828, 20 (offset = 0, 0)
  surface (0, 0) of size 1828, 20: 0x5597cab22fa0
  wm_view_layer for 0x5597cab22fa0 on output 0x5597c9ac3f60
wm_view: Layer Shell, waybar, layer, 3295 (1828.000000, 1101.000000 - 1951.000000, 20.000000) of size 1951, 20 (offset = 0, 0)
  surface (0, 0) of size 1951, 20: 0x5597cab23aa0
  wm_view_layer for 0x5597cab23aa0 on output 0x5597c99822d0
wm_widget (1827.785698, -0.071438 - 1951.428605, 1097.142876)
wm_widget (-385.285736, 0.285702 - 2598.571473, 1461.428596)
---- server end ------

**Comment by CRAG666** [comment]
I have good news, on the .65 waybar scale, if something disappears that with 0.7 does not change to that scale at all, that scale does not affect me at all, so I think that for the moment I will close this too, it may take time for others to develop functions and not get stuck in these. Thanks for everything

**Comment by jbuchermn** [comment]
okay, I just made one little change in pywm. Can you please update and post the same log output again? This should help in order to fix this problem. I can see now where the issue is (it's 1461.42 being rounded down not up).

Let's give it one more try, I'd like to fix the issue if possible.

**Comment by jbuchermn** [comment]
> I have good news, on the .65 waybar scale, if something disappears that with 0.7 does not change to that scale at all, that scale does not affect me at all, so I think that for the moment I will close this too, it may take time for others to develop functions and not get stuck in these. Thanks for everything

okay you're welcome, that's good to hear. If you want, you can still try with 0.7 and I'll try and fix this. I think this is still a bug.
