### ISSUE TITLE
Windows are closed but workspaces are not removed

### ISSUE THREAD

**Issue by CRAG666** [jbuchermn/newm#48]
When I close a window normally the workspaces are readjusted, but something is wrong because sometimes it doesn't happen. for example when I open dbveaber and close it, his workspace still appears, now the same thing happens with thunar and kitty. In the image I have only one terminal open but it seems that there are more windows open when there are none. The workspaces keep appearing and if I move with the touchpad I do it empty because there are no windows in that position.

![only terminal](https://i.ibb.co/hW9brcL/screen-1639087300.png)

Normally when there is only one window and you do ModPress the window is in the center but this does not happen because newm thinks there are more open windows and therefore creates more workspaces

**Comment by CRAG666** [comment]
https://drive.google.com/file/d/1a0mtIBC_AieXdHSP5e7SBKmoPu01y12r/view?usp=sharing
I leave this video to better illustrate this problem.
By the way, also in this video luckily it is possible to see what I commented on the previous issue

**Comment by jbuchermn** [comment]
Yes this is a bug I noticed on occasion, but with the (good-behaving ;) ) apps I use, like alacritty and emacs, this was never reproducable.

I'll try with thunar and dbeaver if I can get this reproducible and fix it. If this appears can you try `newm-cmd clean` - does anything happen?

**Comment by jbuchermn** [comment]
> By the way, also in this video luckily it is possible to see what I commented on the previous issue

Can you point me to the timestamp, where the flickering happens? I noticed another thing, the bottom bar does not disappear completely. But I couldn't make out flickering...

**Comment by CRAG666** [comment]
Well I do not understand why it does not appear in the video but it did happen. If waybar doesn't go away completely and it's quite annoying. Greetings. I hope and this is solved soon

**Comment by jbuchermn** [comment]
does this still happen?

**Comment by CRAG666** [comment]
yes :(

**Comment by CRAG666** [comment]
yes :(

**Comment by CRAG666** [comment]
![error](https://i.ibb.co/3Np437d/screen-1639248243.png)

**Comment by CRAG666** [comment]
exactly the same thing happens that I show in the video

**Comment by jbuchermn** [comment]
What does newm-cmd clean do?

**Comment by jbuchermn** [comment]
Also please post a debug log.

**Comment by CRAG666** [comment]
The command if removes that blank space after executing it

**Comment by CRAG666** [comment]
maybe I can remap the command with which I close windows and then run the clean command

**Comment by CRAG666** [comment]
@jbuchermn  Something like this:
``` python
lambda: [layout.close_focused_view(), layout.command("clean")]
```

**Comment by jbuchermn** [comment]
That's possible but I think the bug should be fixed instead.

If you post a log I can look into it.

**Comment by CRAG666** [comment]
Will there be a way to verify the number of windows open on a monitor and compare it with the number of workspaces if they do not match, do a cleaning or delete the space that does not contain application

**Comment by jbuchermn** [comment]
That's precisely what newm-cmd clean does.

However this shouldn't be necessary at all, if window closing is handled properly.

**Comment by CRAG666** [comment]
Yes I understand, but this happens. Share my log file after opening dbeaver

**Comment by CRAG666** [comment]
https://drive.google.com/file/d/1EPulSVjwl9aXjpUf-0Q387ekZWB_cP_r/view?usp=sharing
this is newm_log

**Comment by jbuchermn** [comment]
That's quite hard.. Unfortunately I can't reproduce it on my machine. If I recall the video correctly DBeaver crashes upon startup... What do I have to do to reproduce these DBeaver crashes?

**Comment by CRAG666** [comment]
Just add some database that you can't connect to. But in the case of dbeaver it happens at any time even when everything runs fine in dbeaver

**Comment by jbuchermn** [comment]
That's quite interesting. Can you post a video and log of dbeaver closing without error yet still this newm error occurring? Thanks.

**Comment by CRAG666** [comment]
@jbuchermn I don't really understand what happened but now what I am mentioning does not happen anymore, I suppose it was related to the scale, now that I have it 0.65 many errors have disappeared. It's pretty weird. That is why I will close the problem for the moment unless this is repeated again, I have been testing for a while and it no longer happened. I guess decimal scales are very unpredictable but at least I found one that solves everything I put in the issues. Again thank you very much
