### ISSUE TITLE
[packaging] Is it allowed/possible to install pywm and newm separately?

### ISSUE THREAD

**Issue by AndersonTorres** [jbuchermn/newm#51]
Hello! I'm Anderson Torres, a maintainer of some packages in [NixOS](http://nixos.org/).
I came across newm by the Github suggestions, and I'm now interested in packaging it.

I noticed that the AUR script you have provided, and it downloads and installs both pywm and newm in the same directory, despite they are being maintained in different repositories.

That being said, and before trying it by myself, I think I should ask: is it necessary to download both sources and install them at the same time?

**Comment by jbuchermn** [comment]
Hi,

first of all: I'd be very happy to see newm packaged on NixOS!

For newm to work pywm is necessary. pywm itself is an abstraction layer and could be used in other projects - but at the moment it is packaged on AUR together with newm for simplicity.

These packages don't need to be installed in the same directory, but newm needs to be able to find pywm in the PYTHONPATH. So in short: It's necessary to download both sources although they need not be in the same package.

**Comment by jbuchermn** [comment]
@AndersonTorres do you need more information?

**Comment by AndersonTorres** [comment]
Not for now.
I will take a 10-day vacation and retake it later, but for now it's OK. I'll close this issue.

Many thanks!
