### ISSUE TITLE
V3 Description Roadmap

### ISSUE THREAD

**Issue by CRAG666** [jbuchermn/newm#52]
It will be possible to add to the v3 readme the roadmap designed for that branch so that it is easier to know how to collaborate

**Comment by jbuchermn** [comment]
That's a good point, I will do that. The current roadmap can actually be found in dev/DEV.org, but I'm going to link that from the README / or maybe put some more detailed information in the README.

**Comment by CRAG666** [comment]
Maybe just set the objectives without being so specific. This is very helpful but your ideas seem great too. But remember that the README is the cover letter of the project. Greetings

**Comment by jbuchermn** [comment]
Just added some information to README

**Comment by CRAG666** [comment]
Cool. It would be great to be able to see progress, that is, at each point on the route map, include the status in parentheses. For example in progress, finished, contributor needed. That will greatly improve how progress is made and how the avenues are shown to those interested

**Comment by jbuchermn** [comment]
Yeah no. This is my free time and I'm not reporting any progress.
