### ISSUE TITLE
how to remove the border in an active window in v0.3

### ISSUE THREAD

**Issue by CRAG666** [jbuchermn/newm#53]
I'm testing the v3 of newm and all his work is incredible, but there is something that personally I do not like is the border of the selected window, is there any configuration to remove this border? Or in any case change the color?

**Comment by CRAG666** [comment]
you can remove the borders with this setting, but i don't know if it's ideal
```python
focus = {
    'distance': 0,
    'width': 0,
    'animate_on_change': False,
    'anim_time': 0
}
```
In any case if I configure something wrong, it tells me if not then I close this issue. Thank you very much and I look forward to the stable version of v3 because it looks great

**Comment by jbuchermn** [comment]
That was indeed not configurable until now. Since the last commits, however, you should be able to do

``py
focus = {
    'color': '#FFBB0011', # change color
    'enabled': False # disable
}

``

**Comment by fedoranvar** [comment]
It removed borders from tiled windows but not from floated

![image](https://user-images.githubusercontent.com/52028706/163323094-ca863aaa-09f4-4f2e-9f7a-1bd4a2cdb55a.png)

**Comment by fedoranvar** [comment]
@jbuchermn 

thanks! it worked!
