### ISSUE TITLE
Tutorial on Arch Linux

### ISSUE THREAD

**Issue by jbuchermn** [jbuchermn/newm#55]
This issue is meant to track instructions and information useful for beginners on how to setup newm on a fresh Arch install.

1. Optional: Install [sway](https://github.com/swaywm/sway) and see if it works (as a sanity check).
2. Install an AUR helper, in this case: `yay` - see [yay](https://github.com/Jguer/yay) for detailed instructions.
3. Execute `yay -S newm-git` (hit enter on `yay`s prompts)
4. Run `start-newm`
5. If this works - setup config: 
```
cd
mkdir -p .config/newm
cp /usr/lib/pythonX.Y/site-packages/newm/default_config.py .config/newm/config.py
vim .config/newm/config.py
```

**Comment by graziel666** [comment]
really thanks for this! i'm the guy from youtube
i got it working! but i have a little problem, i can't find the config file anywhere, neither on .config (but i expected this) or in .local/lib/python3.10/site-packages
there i just don't have the newm folder at all to copy from it

**Comment by jbuchermn** [comment]
You're very welcome.

I see, where to find default_config is not quite obvious, as it depends on the installation method. In your case, it should be in `/usr/lib/pythonX.Y/site-packages/newm/default_config.py`

**Comment by graziel666** [comment]
> You're very welcome.
> 
> I see, where to find default_config is not quite obvious, as it depends on the installation method. In your case, it should be in `/usr[/local]/lib/pythonX.Y/site-packages/newm/default_config.py`
> 
> I'm not quite sure on the `local` as I'm currently not running Arch.

ohhhh thanks! found it, in case someone else need it, it's on
`/usr/lib/pythonX.Y/site-packages/newm/`

**Comment by graziel666** [comment]
well, i'm pretty sure this is my last message haha, i'm happy to inform that all is working perfectly fine
i used your dotfiles and after some poking around i got it all working perfectly fine, there's only one thing that bothers me, and i have no idea how it happened, my scrolling is upside down hahaha

either way, really thanks for the help and for making this, i switched from bspwm and really feel it way better

**Comment by jbuchermn** [comment]
That's great to hear :)

Your scrolling upside down is probably "natural scrolling" which not everybody likes - try:

```py
pywm = {
    'natural_scroll': False
}

```

**Comment by CRAG666** [comment]
https://github.com/CRAG666/dotfiles/blob/master/config/newm/config.py
These are my dotfiles maybe they will help you with some extra things that the original creator dotfiles do not include
I see you are on arch linux. If you want to have the latest version or maybe some experimental branch ideally you use `yay -G newm-git` navigate to that folder and clone newm(choose the branch you like) and pywm(the branch you use in newm) then just do `makepkg -sic` this way you will have a better and more customized installation

**Comment by graziel666** [comment]
Oh great thanks! I'll give it a look tomorrow if I have the time
Still now I'm back on bspwm since, for some reason, when i lock the screen instead of showing me the password pop up, it just do the effect and i can't make any input more than switching to other tty and sudo reboot

**Comment by CRAG666** [comment]
> Oh great thanks! I'll give it a look tomorrow if I have the time Still now I'm back on bspwm since, for some reason, when i lock the screen instead of showing me the password pop up, it just do the effect and i can't make any input more than switching to other tty and sudo reboot

do you use systemd? If you use systemd you can review the documentation or my dotfiles there is a configuration with systemd and lock works perfect

**Comment by jbuchermn** [comment]
Be aware that default config requires alacritty for the Lock Screen.

Also, check @CRAG666 s config for kitty.

If that does not work, could you post any log files?

**Comment by CRAG666** [comment]
The terminal I use is kitty but I have already tried others and it works perfectly

**Comment by graziel666** [comment]
@jbuchermn @CRAG666  alright i didn't knew i was on systemd hahahaha that worked, now i'm giving an eye to @CRAG666 config files
really thanks for all the help :smile:

**Comment by jbuchermn** [comment]
Yup you're right :)
