### ISSUE TITLE
How do I install v0.3 branch?

### ISSUE THREAD

**Issue by DimitrisMilonopoulos** [jbuchermn/newm#60]
Used aur for 0.2 or that's the version I believe I have.

Is there a way to test out v0.3?

Also if you have 3 monitors is it possible to jump to a specific one? Saw some arguments on the layout functions but wasn't sure I could pass an index.

Thank you!

**Comment by CRAG666** [comment]
It's easy just do yay -G new-git, then navigate to the folder downloaded by yay, and clone pywm and newm there (when clone indicates the branch) then just do a makepkg -sic

**Comment by CRAG666** [comment]
![folder](https://i.ibb.co/QKJypXt/screen-1644452382.png)

**Comment by DimitrisMilonopoulos** [comment]
Makes a lot of sense, oh well there goes my weekend tinkering around. Wayland is just superior.

I bought a 4k monitor and video playback was SUPER SLOW. Launched newm, no lag at all.
