### ISSUE TITLE
Recent renderer changes on v0.3 / debug - performance issues

### ISSUE THREAD

**Issue by jbuchermn** [jbuchermn/newm#61]
Recently there have been a lot of changes on v0.3 regarding rendering and timing.

This issue is meant to track any performance related problems happening now, especially non-smooth animations and gestures (low fps, dropped frames).

If you're experiencing any issues: Please check out the debug branch on pywm (v0.3 on newm), run newm for a very short time (maybe two or three low-performance animations, like 5 seconds in total) and upload the log file. Thanks!

@CRAG666 @DimitrisMilonopoulos

**EDIT - Findings**
- The current timing method does not cope well with more than one monitor. In this case, many skipped frames and the like appear.

**Comment by CRAG666** [comment]
@jbuchermn  understrood :)

**Comment by CRAG666** [comment]
I'm currently on the debug branch. Animations are clunky and slow on the second monitor on the main monitor they work fine

**Comment by CRAG666** [comment]
@jbuchermn log https://drive.google.com/file/d/1ovHpkv5gnig5MlzmXWT3xTpuod1sCLcX/view?usp=sharing

**Comment by CRAG666** [comment]
my current config https://github.com/CRAG666/dotfiles/blob/master/config/newm/configV3.py

**Comment by jbuchermn** [comment]
Thanks for the log, I'm studying it at the moment.

At first sight it looks like the two monitors perform quite differently (one looks okay, one looks very bad) - is this true, or do you see equally bad animations on both screens?

**Comment by jbuchermn** [comment]
Also.. I just realized, I made some git errors, so only now is damage branch up-to-date with v0.3. Would you mind trying again?

**Comment by CRAG666** [comment]
@jbuchermn I just updated and if the error is still present, as I already mentioned, the error only occurs on the second monitor

**Comment by jbuchermn** [comment]
Can you also upload a new log?

**Comment by CRAG666** [comment]
I'm a dumb v3 compiler and I don't debug. Debug works perfect.

**Comment by CRAG666** [comment]
the debug branch works very well, no latency or delays in the animations, everything goes very smoothly

**Comment by jbuchermn** [comment]
That‘s good to hear, although I'm not really confident this is consistent. For me, I do see occasional slow animations. Something about the timing is still off...

**Comment by CRAG666** [comment]
@jbuchermn v3 already has the debug changes?

**Comment by CRAG666** [comment]
If there is a delay I admit it but it is minimal very very minimal but if it improves it would be fine but for now I am satisfied as it is because it is the best without exaggerating the wm

**Comment by jbuchermn** [comment]
> @jbuchermn v3 already has the debug changes?

At the moment not. But I want to merge soon.

However, I just pushed major changes (again...) to debug. Can you try and see if there is lag or are any artifacts, ...? For me it appears to be more performant now.

Btw... renderer_mode does not need to be set anymore (also it has new values, `wlr` for `passthrough` and `pywm` for what was `direct` / `indirect`)

**Comment by CRAG666** [comment]
thank, right now check the new changes and its configuration in nix

**Comment by CRAG666** [comment]
@jbuchermn the debug branch works perfect. The experience is smoother now. I don't know if it has anything to do with it, but the representation of colors had a significant change. The colors are very vivid! this is amazing.

**Comment by jbuchermn** [comment]
That's great to hear :) I just merged debug into v0.3
