### ISSUE TITLE
Keyboard layout variant not supported?

### ISSUE THREAD

**Issue by Phundrak** [jbuchermn/newm#62]
I haven’t found so far a way to enable the `bepo_afnor` variant so work with the `fr` keyboard. What I tried so far:
```python
pywm = {
    "xkb_layout": "fr",
    "xkb_variant": "bepo_afnor",
    "xkb_options": "caps:ctrl_modifier",
}
```
and
```python
pywm = {
    "xkb_layout": "fr",
    "XkbVariant": "bepo_afnor",
    "xkb_options": "caps:ctrl_modifier",
}
```
in `$HOME/.config/newm/config.py`, and launching newm with the following script:
```bash
#!/bin/bash
XKB_DEFAULT_LAYOUT="fr"
XKB_DEFAULT_VARIANT="bepo_afnor"
start-newm -d
```
The layout and the options seem to be set without an issue, but I have no idea how to set the variant.

Just in case someone tries and succeed at setting the variant, [here is a map of the layout](https://download.tuxfamily.org/dvorak/wiki/images/Bepo-1.1-complet.png) so you don’t get lost.

**Comment by Phundrak** [comment]
I just realized this is the job of pywm, not newm, so I looked at its code and the `wm_config` struct defined in `include/wm/wm_config.h` file does not have a member dedicated to the variant. I’ll report it as an issue there.

**Comment by jbuchermn** [comment]
Thanks, that shouldn't be a big thing. So I'll try and add it quickly'

**Comment by jbuchermn** [comment]
Have a look at the latest pywm commit, this should introduce `pywm.xkb_variant` (haven't tried if it works to be honest)

**Comment by Phundrak** [comment]
It seems to work!
--
Lucien “Phundrak” Cartier-Tilet

<https://phundrak.com> (Français)

<https://phundrak.com/en> (English)

Sent from GNU/Emacs

**Comment by jbuchermn** [comment]
Great, I'll close this issue for now.
