### ISSUE TITLE
Cannnot resume from suspend.

### ISSUE THREAD

**Issue by Alan-Kuan** [jbuchermn/newm#68]
Hi, I found that every time after my computer resumed from suspension, the view of my desktop showed up a little while and then the WM just crashed.

Does this have something to do with my display manager or anything else?

**Comment by jbuchermn** [comment]
I've seen issues like this related to seat management. However it is quite hard to tell.

Can you upload a log file (`~/.config/newm_log`) after such a crash?

**Comment by Alan-Kuan** [comment]
Sure, the following is the log it generated.
[newm_log](https://github.com/jbuchermn/newm/files/8085024/newm_log.txt)

**Comment by jbuchermn** [comment]
Thanks, I've seen the same issue on my machine. Latest pywm commit appears to fix it - can you update and verify?

**Comment by Alan-Kuan** [comment]
Hello, I tried updating newm with yay. However, when it started to build, I encountered an error and it printed a bunch lines of unformatted error message.

Here is the log of it.
[error_log.txt](https://github.com/jbuchermn/newm/files/8088196/error_log.txt)

**Comment by jbuchermn** [comment]
That's a weird error unrelated to the latest commit. It looks like pywm and / or wlroots are not checked out properly. You are on master I assume?

In any case, can you try clean-building with yay?

**Comment by Alan-Kuan** [comment]
May I ask you which branches of newm and pywm should I use to build and install?

I tried checkout to `debug` of both; although newm was successfully installed, it could not get started.

BTW, I tried clean-building with yay, but I still encountered previous error.

**Comment by Alan-Kuan** [comment]
Oh, I see. However, I couldn't build pywm on master. The followings is the steps I used to build:
```sh
git clone https://github.com/jbuchermn/pywm && cd pywm
git submodule init
git submodule update
python3 setup.py build
```
After I executed the last line, the [error](#issuecomment-1042850553) occurred.

**Comment by jbuchermn** [comment]
Ah I see now - I accidentally updated the subproject commit in my last commit on master which is obvious bullshit.

So, what you're doing is correct, but master was (I just pushed) broken. Can you try again?

**Comment by Alan-Kuan** [comment]
Oops, although I could resume from suspension, there's another problem that caused the WM crashed right after resuming.

After resuming, I exited the terminal I opened before suspension, and then it crashed.
I also found that if it resumed with only a terminal, it would not happen.
However, if it resumed with a terminal and Firefox, the problem would occur.

Here is the log. I take the part related to the issue.
[newm_log.txt](https://github.com/jbuchermn/newm/files/8093524/newm_log.txt)

**Comment by Alan-Kuan** [comment]
I found that the issue is related to the display manager I used.

I encountered it when I used lightdm, but it disappeared if I simply used greetd.

**Comment by jbuchermn** [comment]
Hey,

it seems, lightdm is doing something weird with the seat, which pywm does not expect, causing the segfault in pywm - probably this is not a big issue to fix.

However, as I'm not running any display manager and I'm not really interested in a login screen which requires the xserver to start, I can't debug that on my machine. (As a matter of fact I did try to get lightdm with newm running on my nixOS but couldn't within 15mins). So I suppose I'm going to follow sway in not officially supporting display managers (https://github.com/swaywm/sway/pull/3634#issuecomment-462779163).

I'll leave this open for now, in case someone is able to find the bug.

**Comment by Alan-Kuan** [comment]
Hey,

I see. I'll look for other work arounds or perhaps just go with greetd.

Again, thank you for fixing the bug that it could not resume from suspension!
