### ISSUE TITLE
Disable focus on mako notifications

### ISSUE THREAD

**Issue by iCultureBud** [jbuchermn/newm#69]
Is there a way to prevent mako notification popups from getting focus or is a fix coming in v.03?

**Comment by jbuchermn** [comment]
I assume, you're on master? This should already be fixed on v0.3 - feel free to take a look there, if it works for you.

**Comment by iCultureBud** [comment]
Ah okay. I only asked because I was unsure what you meant by "better integration" :D

Thank's again
