### ISSUE TITLE
 can't use the touch panel to click

### ISSUE THREAD

**Issue by CRAG666** [jbuchermn/newm#7]
I can't use the touch panel to click with one finger, with two and with three, everything else works perfectly

**Comment by zphixon** [comment]
Are you talking about tap-to-click? I have a [PR for pywm](https://github.com/jbuchermn/pywm/pull/1) implementing this

**Comment by CRAG666** [comment]
yes, Is exactly what i want

**Comment by CRAG666** [comment]
![my current config](https://i.ibb.co/RpvCQxt/screen-1636646804.png)
I will try to add that to the startup configuration, another thing I noticed is that the rendering of is a bad thing compared to sway I notice it a lot in the textures of the letters. Thanks I close the problem if I can solve it

**Comment by CRAG666** [comment]
In which branch was this implemented, to build from there

**Comment by jbuchermn** [comment]
It's not yet merged but will be into master (v0.1)
