### ISSUE TITLE
XWayland Views are pixelated when Display is scaled

### ISSUE THREAD

**Issue by iCultureBud** [jbuchermn/newm#73]
Applications launched under XWayland are pixelated.

Do you guys experience the same issue?

**Comment by jbuchermn** [comment]
Yeah that's an X issue. X does not have a sensible notion of display scale (one that supports mixed-dpi setups). Check the issues on sways GitHub for more information.

In the end: XWayland views should appear on newm the same way they do on sway and that's as good as it gets for legacy software. If there is a difference compared to sway, I'm happy to take a look.

**Comment by iCultureBud** [comment]
Oh yes I forgot about this issue on sway...
