### ISSUE TITLE
Meaning of the options in blur

### ISSUE THREAD

**Issue by CRAG666** [jbuchermn/newm#78]
{"blur": {"radius": 4, "passes": 4}}
@jbuchermn What does each of the options mean, I am playing with them with this I plan to expand the documentation and tricks

**Comment by jbuchermn** [comment]
These are passes and radius in pixel for the Kawase blur algorithm.

In short: Increase these to get "more blur". A higher value for `passes` has a higher impact than a higher value for `radius`.

**Comment by Pandademic** [comment]
@jbuchermn can we close this issue?
