### ISSUE TITLE
rofi wayland does not work

### ISSUE THREAD

**Issue by CRAG666** [jbuchermn/newm#8]
i use a fork of rofi that works with wayland, currently i use it with sway, but i want to switch to this wm, but rofi doesn't work
(process:7509): Wayland-ERROR **: 09:04:21.390: Rofi on wayland requires support for the layer shell protocol

**Comment by jbuchermn** [comment]
As the message states, layer shell isn't supported by newm. To be honest, it's not that high on the list of my priorities, as I think all functionality that relies on it needs to be more tightly integrated into a compositor like newm (with a focus on animations and gestures)

**Comment by CRAG666** [comment]
I saw that I already added support for rofi, it has already advanced a bit now the error change to 'core' generated

**Comment by jbuchermn** [comment]
Basic support for layer shell now is implemented. There are some things that won't work now, like exclusive zones (e.g. waybar) or popups. But rofi should.

**Comment by CRAG666** [comment]
it already works, it's great incredible

**Comment by CRAG666** [comment]
I can even select the screen to share in meet and other applications

**Comment by CRAG666** [comment]
This is amazing, do you think it's time to close this?

**Comment by jbuchermn** [comment]
Yes let's close it. If you encounter any issues with layer surfaces, just open a new one.
