### ISSUE TITLE
config changes regarding keybinding config

### ISSUE THREAD

**Issue by jbuchermn** [jbuchermn/newm#80]
Be aware that the most recent commit breaks existing configs.

Instead of

```py
mod = PYWM_MOD_LOGO
key_bindings = lambda layout: [("M-x", ...)]
```

use

```py
mod = "L" # or "A", "C", "1", "2", "3"
key_bindings = lambda layout: [(mod+"-x", ...)]
```

It's added to the docs but for everyone using v0.3 probably rather unexpected.

**Comment by CRAG666** [comment]
@jbuchermn now how to use modpress?

**Comment by jbuchermn** [comment]
The keys themselves haven't changed. Try "A", "L", "C", "1", "2", "3". Which these are in fact depends on your keyboard layout.

For ModPress just use "L-", if e.g. your Mod is Logo.

**Comment by CRAG666** [comment]
@jbuchermn thanks, is amazing the new config

**Comment by Pandademic** [comment]
@jbuchermn should this be a the top of readme as a notice?

**Comment by CRAG666** [comment]
unfortunately I am not able to use the alrgr key :( in swaywm the altgr key can be used with the following command
set $super Mod5

**Comment by jbuchermn** [comment]
As I said this depends on your layout, and I have no issues so I can't tell what's going wrong on your setup.

You can check pywms pywm.py (first couple lines) to see that Mod5 is mapped to "3"

**Comment by jbuchermn** [comment]
> @jbuchermn should this be a the top of readme as a notice?

Yeah that's a good idea, this should be added - at least once v0.3 is released. I think there are some other config changes.

**Comment by Pandademic** [comment]
@jbuchermn  okay , maybe in the `configuration.md` doc?

**Comment by CRAG666** [comment]
@jbuchermn I understand what you are telling me, the keyboard layout I use is 'es'. if mod5 is '3' then something like the following should work
        ("3-w", layout.change_focused_view_workspace),

**Comment by CRAG666** [comment]
But so far I can't get it to work :(

**Comment by jbuchermn** [comment]
Yeah you probably need to debug this in key_processor or pywm. I'm not that interested in this issue as I'm pretty certain it's got sth to do with libinput config or sth like that.

Just to make sure I just test on my MacBook where "3-w" indeed triggers on right alt.

**Comment by jbuchermn** [comment]
One thing to be aware of (maybe this is your issue), is as AltGr changes many keys, keybindings need to be defined accordingly. On my keymap e.g. AltGr+E becomes € - so I need to use "3-EuroSign" for AltGr+E.

This is certainly inconvenient if you're not willing to dive into the code, so I'll think of some way to improve on this - either by documentation, or by providing a newm-cmd to log, which keys are hit. Depending on how wlroots interacts with libinput this can probably be changed to not be necessary but I don't want to spend too much time on that edge case - so PRs are welcome.

**Comment by jbuchermn** [comment]
okay turns out this was rather fast to change, I just pushedd

**Comment by CRAG666** [comment]
Thanks for taking the time. Perhaps I was very demanding with this, an apology, but the altgr key is comfortable for me because I am left-handed. Thank you very much again.

**Comment by CRAG666** [comment]
You are amazing, I can finally use altgr this is fabulous. I'm really very happy
