### ISSUE TITLE
newm v0.3 and v0.2  buggy and slow 

### ISSUE THREAD

**Issue by hackedWifi** [jbuchermn/newm#83]
I have installed both versions of pywm and newm (v0.2 and v0.3) and keep getting the following issue: 
As soon as I open kitty I get the following issue on the screenshot provided. (right half part of the screenshot) I can't type exit to quit kitty.

I am on Gentoo and my machine is Dell XPS 15 9550 i5 6700HQ, 16G RAM, Intel iGPU HD 530 (default) and NVIDIA GTX 960M

![newm](https://user-images.githubusercontent.com/22781207/157351125-31598a3b-f254-4edf-a1a1-5fa89ee994c0.png)

This happens while pressing L+touchpad to resize a window
![20220308_17h29m47s_grim](https://user-images.githubusercontent.com/22781207/157355226-ffdfb450-7194-4b44-9676-b49126ef2519.png)

[https://pastebin.com/PsgscdBb](url)

**Comment by Pandademic** [comment]
@hackedWifi how is it for you now?

**Comment by jbuchermn** [comment]
Latest pywm commit on v0.3 should work even without a background

**Comment by hackedWifi** [comment]
> @hackedWifi how is it for you now?

After setting the background to my correct path. I was able to get it working. Now, once I launch the lock screen. Everything freezes. I can't input a password. The lock screen was working on v0.2. everything else is working fine

**Comment by hackedWifi** [comment]
> Latest pywm commit on v0.3 should work even without a background

How can I turn all the animations off? I have set anim=False in background and output but I still get some while resizing windows

**Comment by jbuchermn** [comment]
Can you be a bit more specific? Which animations do you get? Background or windows moving, or anything else? Resizing by Logo+two finger swipe?

In general,there are certain animations, that can be disabled, but it's not meant to run without any animations / gestures.

For the Lock screen, that's probably a confit issue and can be a bit unnerving to debug. You can use newm-cmd unlock from another terminal while debugging.

**Comment by hackedWifi** [comment]
> 

Regarding the animation. I would like to know which ones can be disabled. The lockused to work in version v0.2. nothing was change in the config besides the background and terminal to kitty

**Comment by Pandademic** [comment]
@jbuchermn did we change anything in the lock? Also could this be due to a conflict of some sort between 0.2 and 0.3?

**Comment by jbuchermn** [comment]
Set animations to false in the configs and you will see which animations can be disabled. I haven't actually tried that in a long time as the only use case i ever saw was optimising for vnc speed, where moving backgrounds take a big toll. You should be able to disable moving backgrounds, fullscreen windows, moving windows around and the like...

**Comment by jbuchermn** [comment]
> @jbuchermn did we change anything in the lock? Also could this be due to a conflict of some sort between 0.2 and 0.3?

That's a good point, there might be a conflict.

Try running

newm-panel-basic lock 

in a new terminal and see if this crashes.

**Comment by Pandademic** [comment]
@hackedWifi `newm-panel-basic lock`

**Comment by Pandademic** [comment]
@hackedWifi can you post your log?

**Comment by hackedWifi** [comment]
> > @jbuchermn did we change anything in the lock? Also could this be due to a conflict of some sort between 0.2 and 0.3?
> 
> That's a good point, there might be a conflict.
> 
> Try running
> 
> newm-panel-basic lock
> 
> in a new terminal and see if this crashes.

I have done that. The lock shows in the terminal, but it won't take input. I will try to get a log when I am on my laptop.
When I launch it with L+p I get a blurred background, then after 2 seconds a empty terminal pop up. I close it by typing exit, and newm crashes. Only the cursor is responsive

**Comment by hackedWifi** [comment]
> > @jbuchermn did we change anything in the lock? Also could this be due to a conflict of some sort between 0.2 and 0.3?
> 
> That's a good point, there might be a conflict.
> 
> Try running
> 
> newm-panel-basic lock
> 
> in a new terminal and see if this crashes.

I have done that. The lock shows in the terminal, but it won't take input. I will try to get a log when I am on my laptop.
When I launch it with L+p I get a blurred background, then after 2 seconds a empty terminal pop up. I close it by typing exit, and newm crashes.

**Comment by hackedWifi** [comment]
I have solved the lock issue. The solution was to launch `dbus-run-session start-new -d' from tty1. I don't use any greeter. 
I have solved the initial issue on this OP by setting the background. 
Thanks to everyone
