### ISSUE TITLE
I can't share screen

### ISSUE THREAD

**Issue by CRAG666** [jbuchermn/newm#9]
First of all this project is incredible and beautiful, the way of moving between windows is incredible. I work as a remote software developer so I have daily meetings where I share my screen, but I have tried to do it in newm and I just couldn't. In swaywm everything works correctly. Any solution?

**Comment by jbuchermn** [comment]
Thanks for the nice words.

I just tried screensharing using [xdg-desktop-portal-wlr](https://github.com/emersion/xdg-desktop-portal-wlr) and a webrtc test page, which appeared to work. However, on sway it's sufficient to run `xdg-desktop-portal -r` and it will automatically start `xdg-desktop-portal-wlr` - this didn't work for me.

But starting `xdg-desktop-portal-wlr -r` did the trick on newm. Can you try?

**Comment by jbuchermn** [comment]
This also did the trick for me (see README of xdg-desktop-portal-wlr):

```
dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP=wlroots
```
If this works I'll add it to the README

**Comment by CRAG666** [comment]
![my current config](https://i.ibb.co/RpvCQxt/screen-1636646804.png)
I will try to add that to the startup configuration, another thing I noticed is that the rendering of is a bad thing compared to sway I notice it a lot in the textures of the letters. Thanks I close the problem if I can solve it

**Comment by jbuchermn** [comment]
Can you elaborate a bit on the rendering issues? Do you mean in general, or during screen sharing? Which apps is this most notable?

**Comment by CRAG666** [comment]
I noticed it before trying to share screen and it is general, first I noticed it in kitty the terminal that I use and then using the other applications. I don't have such a powerful equipment, it's a thinkpad l450, but in sway the textures and rendering look pretty good in sway

**Comment by jbuchermn** [comment]
Yeah your hardware should not be an issue. If it were, you'd be seeing lagging animations and the such...

Can you describe what the issues are? Is it blurry? Are there artefacts? A screenshot would help

**Comment by CRAG666** [comment]
Well now I'm on sway for dual monitor issues (I hope it will be implemented soon in newm) so I can't send a screenshot, but the problem is that the letters and some graphic parts are blurred, as I say animations and more things are fine in fact very close to perfect

**Comment by jbuchermn** [comment]
Okay, blurry can happen if things are rounded wrong. So it's probably a separate bug. When you encounter it again, please open a new issue and include a screenshot as well as the log file after hitting F1.

Btw, multi monitor is working, but still in an early stage. If you're interested, use branches v0.2 both of newm and pywm.
