### ISSUE TITLE
Documentation v0.3

### ISSUE THREAD

**Issue by jbuchermn** [jbuchermn/newm#93]
This issue is meant to track all necessary documentation in order to release v0.3
- [x] Config keys
  - [x] New native bar config
  - [x] `panels.[bar,top_bar,bottom_bar]`
  - [x] `gesture_bindings` and `gestures` 
  - [x] `view.rules`
  - [x] `view.accept_fullscreen`
  - [x] `energy`
  - [x] `synchronous_update`
  - [x] `enable_unlock_command`
  - [x] `focus`
  - [x] `view.ssd`
- [x] pywm stuff
- [x] general gesture stuff
- [x] newm helpers

Please add missing stuff.

**Comment by CRAG666** [comment]
I will list what for me is still unfinished or lacks clarity:
* newm.helpers
* some layout functions(layout.move_in_stack, layout.swallow_focused_view)
* swipe
* bar
* grid
@jbuchermn Thank you very much for v3, the truth is a great improvement over v2. I will help with everything in my power with this issue. For example I will update the look_and_feel.md to include how to insert gtk2 options with ease

**Comment by jbuchermn** [comment]
I'll close this for now, as most of the documentation is there. Please feel free to open issues (or better PRs ;) )
