### ISSUE TITLE
add option visible_normal and visible_fullscreen  to bar and bottom_bar

### ISSUE THREAD

**Issue by CRAG666** [jbuchermn/newm#94]
@jbuchermn I love the new configuration structure, however I do miss that the bar only shows up when I press Modpress. I personally don't want to see the bar all the time. It will be possible to have an option that of that behavior

**Comment by CRAG666** [comment]
top bar works super great that animation looks very fine, I love it. I would like to have visible_normal and visible_fullscreen in bar and bottom_bar

**Comment by jbuchermn** [comment]
I just pushed a fix that adds `visible_normal` and `visible_fullscreen` to `bottom_bar` and `bar` - does it work?

**Comment by CRAG666** [comment]
@jbuchermn  Thanks
