### ISSUE TITLE
IPC socket?

### ISSUE THREAD

**Issue by fedoranvar** [jbuchermn/newm#97]
Good day to you!

Is there any possibility for IPC socket system, similar to `swaymsg` or `tmux`, for controlling WM via shell-commands?

Thank you!

**Comment by CRAG666** [comment]
I think it is not necessary since you can communicate through python. If you want to control newm create a python script where you import layout if you want to execute some actions.

**Comment by fedoranvar** [comment]
Got it. Thank you!

**Comment by jbuchermn** [comment]
Just as an additional remark.. something like this does exist, although the functionality is very limited at the moment - `newm-cmd`. It works via dbus.

@CRAG666 spent some time recently on improving its usage, which could be the basis to add more commands
